// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace nl.boxplosive.BackOffice.Mvc.Controllers
{
    public partial class LoyaltyProgramController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public LoyaltyProgramController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected LoyaltyProgramController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Index()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Live()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Live);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Staging()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Staging);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public LoyaltyProgramController Actions { get { return MVC.LoyaltyProgram; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "LoyaltyProgram";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "LoyaltyProgram";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string Live = "Live";
            public readonly string Staging = "Staging";
            public readonly string SignOutUser = "SignOutUser";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string Live = "Live";
            public const string Staging = "Staging";
            public const string SignOutUser = "SignOutUser";
        }


        static readonly ActionParamsClass_Index s_params_Index = new ActionParamsClass_Index();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Index IndexParams { get { return s_params_Index; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Index
        {
            public readonly string loyaltyProgram = "loyaltyProgram";
        }
        static readonly ActionParamsClass_Live s_params_Live = new ActionParamsClass_Live();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Live LiveParams { get { return s_params_Live; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Live
        {
            public readonly string loyaltyProgram = "loyaltyProgram";
            public readonly string loyaltyProgramId = "loyaltyProgramId";
            public readonly string submitButton = "submitButton";
        }
        static readonly ActionParamsClass_Staging s_params_Staging = new ActionParamsClass_Staging();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Staging StagingParams { get { return s_params_Staging; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Staging
        {
            public readonly string loyaltyProgram = "loyaltyProgram";
            public readonly string model = "model";
            public readonly string submitButton = "submitButton";
        }
        static readonly ActionParamsClass_SignOutUser s_params_SignOutUser = new ActionParamsClass_SignOutUser();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SignOutUser SignOutUserParams { get { return s_params_SignOutUser; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SignOutUser
        {
            public readonly string actionResultOverride = "actionResultOverride";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string Live = "Live";
                public readonly string ShareLoyaltyPoints = "ShareLoyaltyPoints";
                public readonly string Staging = "Staging";
            }
            public readonly string Live = "~/Views/LoyaltyProgram/Live.cshtml";
            public readonly string ShareLoyaltyPoints = "~/Views/LoyaltyProgram/ShareLoyaltyPoints.cshtml";
            public readonly string Staging = "~/Views/LoyaltyProgram/Staging.cshtml";
            static readonly _EditorTemplatesClass s_EditorTemplates = new _EditorTemplatesClass();
            public _EditorTemplatesClass EditorTemplates { get { return s_EditorTemplates; } }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public partial class _EditorTemplatesClass
            {
                static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
                public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
                public class _ViewNamesClass
                {
                    public readonly string LoyaltyPointsProgram = "LoyaltyPointsProgram";
                    public readonly string LoyaltyPointsProgramDraftModel = "LoyaltyPointsProgramDraftModel";
                }
                public readonly string LoyaltyPointsProgram = "~/Views/LoyaltyProgram/EditorTemplates/LoyaltyPointsProgram.cshtml";
                public readonly string LoyaltyPointsProgramDraftModel = "~/Views/LoyaltyProgram/EditorTemplates/LoyaltyPointsProgramDraftModel.cshtml";
            }
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_LoyaltyProgramController : nl.boxplosive.BackOffice.Mvc.Controllers.LoyaltyProgramController
    {
        public T4MVC_LoyaltyProgramController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int loyaltyProgram);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index(int loyaltyProgram)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "loyaltyProgram", loyaltyProgram);
            IndexOverride(callInfo, loyaltyProgram);
            return callInfo;
        }

        [NonAction]
        partial void LiveOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int loyaltyProgram);

        [NonAction]
        public override System.Web.Mvc.ActionResult Live(int loyaltyProgram)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Live);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "loyaltyProgram", loyaltyProgram);
            LiveOverride(callInfo, loyaltyProgram);
            return callInfo;
        }

        [NonAction]
        partial void LiveOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int loyaltyProgramId, string submitButton);

        [NonAction]
        public override System.Web.Mvc.ActionResult Live(int loyaltyProgramId, string submitButton)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Live);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "loyaltyProgramId", loyaltyProgramId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "submitButton", submitButton);
            LiveOverride(callInfo, loyaltyProgramId, submitButton);
            return callInfo;
        }

        [NonAction]
        partial void StagingOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int loyaltyProgram);

        [NonAction]
        public override System.Web.Mvc.ActionResult Staging(int loyaltyProgram)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Staging);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "loyaltyProgram", loyaltyProgram);
            StagingOverride(callInfo, loyaltyProgram);
            return callInfo;
        }

        [NonAction]
        partial void StagingOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int loyaltyProgram, nl.boxplosive.BackOffice.Mvc.Models.LoyaltyPointsProgram.LoyaltyProgramModel model, string submitButton);

        [NonAction]
        public override System.Web.Mvc.ActionResult Staging(int loyaltyProgram, nl.boxplosive.BackOffice.Mvc.Models.LoyaltyPointsProgram.LoyaltyProgramModel model, string submitButton)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Staging);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "loyaltyProgram", loyaltyProgram);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "submitButton", submitButton);
            StagingOverride(callInfo, loyaltyProgram, model, submitButton);
            return callInfo;
        }

        [NonAction]
        partial void SignOutUserOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, System.Web.Mvc.ActionResult actionResultOverride);

        [NonAction]
        public override System.Web.Mvc.ActionResult SignOutUser(System.Web.Mvc.ActionResult actionResultOverride)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SignOutUser);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "actionResultOverride", actionResultOverride);
            SignOutUserOverride(callInfo, actionResultOverride);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
