// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace nl.boxplosive.BackOffice.Mvc.Controllers
{
    public partial class ManageVersionMessageController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ManageVersionMessageController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected ManageVersionMessageController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult AddProduct()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddProduct);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GetProducts()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetProducts);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GetGroups()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetGroups);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ValidateAndSetMultiProducts()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ValidateAndSetMultiProducts);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult ConfirmProductUpload()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.ConfirmProductUpload);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.FileContentResult GetDownloadProductsFileResult()
        {
            return new T4MVC_System_Web_Mvc_FileContentResult(Area, Name, ActionNames.GetDownloadProductsFileResult);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GetPromotions()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetPromotions);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult UploadImage()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UploadImage);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult UploadImageCKEditor()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UploadImageCKEditor);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ManageVersionMessageController Actions { get { return MVC.ManageVersionMessage; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "ManageVersionMessage";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "ManageVersionMessage";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string Edit = "Edit";
            public readonly string Delete = "Delete";
            public readonly string AddProduct = "AddProduct";
            public readonly string GetProducts = "GetProducts";
            public readonly string GetGroups = "GetGroups";
            public readonly string ValidateAndSetMultiProducts = "ValidateAndSetMultiProducts";
            public readonly string ConfirmProductUpload = "ConfirmProductUpload";
            public readonly string GetDownloadProductsFileResult = "GetDownloadProductsFileResult";
            public readonly string GetPromotions = "GetPromotions";
            public readonly string UploadImage = "UploadImage";
            public readonly string UploadImageCKEditor = "UploadImageCKEditor";
            public readonly string SignOutUser = "SignOutUser";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string Edit = "Edit";
            public const string Delete = "Delete";
            public const string AddProduct = "AddProduct";
            public const string GetProducts = "GetProducts";
            public const string GetGroups = "GetGroups";
            public const string ValidateAndSetMultiProducts = "ValidateAndSetMultiProducts";
            public const string ConfirmProductUpload = "ConfirmProductUpload";
            public const string GetDownloadProductsFileResult = "GetDownloadProductsFileResult";
            public const string GetPromotions = "GetPromotions";
            public const string UploadImage = "UploadImage";
            public const string UploadImageCKEditor = "UploadImageCKEditor";
            public const string SignOutUser = "SignOutUser";
        }


        static readonly ActionParamsClass_Edit s_params_Edit = new ActionParamsClass_Edit();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Edit EditParams { get { return s_params_Edit; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Edit
        {
            public readonly string version = "version";
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_Delete s_params_Delete = new ActionParamsClass_Delete();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Delete DeleteParams { get { return s_params_Delete; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Delete
        {
            public readonly string version = "version";
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_AddProduct s_params_AddProduct = new ActionParamsClass_AddProduct();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AddProduct AddProductParams { get { return s_params_AddProduct; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AddProduct
        {
            public readonly string gtin = "gtin";
        }
        static readonly ActionParamsClass_GetProducts s_params_GetProducts = new ActionParamsClass_GetProducts();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetProducts GetProductsParams { get { return s_params_GetProducts; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetProducts
        {
            public readonly string term = "term";
            public readonly string parentId = "parentId";
        }
        static readonly ActionParamsClass_GetGroups s_params_GetGroups = new ActionParamsClass_GetGroups();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetGroups GetGroupsParams { get { return s_params_GetGroups; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetGroups
        {
            public readonly string term = "term";
        }
        static readonly ActionParamsClass_ValidateAndSetMultiProducts s_params_ValidateAndSetMultiProducts = new ActionParamsClass_ValidateAndSetMultiProducts();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ValidateAndSetMultiProducts ValidateAndSetMultiProductsParams { get { return s_params_ValidateAndSetMultiProducts; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ValidateAndSetMultiProducts
        {
            public readonly string source = "source";
        }
        static readonly ActionParamsClass_ConfirmProductUpload s_params_ConfirmProductUpload = new ActionParamsClass_ConfirmProductUpload();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ConfirmProductUpload ConfirmProductUploadParams { get { return s_params_ConfirmProductUpload; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ConfirmProductUpload
        {
            public readonly string source = "source";
        }
        static readonly ActionParamsClass_GetDownloadProductsFileResult s_params_GetDownloadProductsFileResult = new ActionParamsClass_GetDownloadProductsFileResult();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetDownloadProductsFileResult GetDownloadProductsFileResultParams { get { return s_params_GetDownloadProductsFileResult; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetDownloadProductsFileResult
        {
            public readonly string products = "products";
            public readonly string productSetLabel = "productSetLabel";
        }
        static readonly ActionParamsClass_GetPromotions s_params_GetPromotions = new ActionParamsClass_GetPromotions();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetPromotions GetPromotionsParams { get { return s_params_GetPromotions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetPromotions
        {
            public readonly string term = "term";
        }
        static readonly ActionParamsClass_UploadImage s_params_UploadImage = new ActionParamsClass_UploadImage();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_UploadImage UploadImageParams { get { return s_params_UploadImage; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_UploadImage
        {
            public readonly string postedFileFieldName = "postedFileFieldName";
            public readonly string urlFieldName = "urlFieldName";
            public readonly string urlFieldId = "urlFieldId";
        }
        static readonly ActionParamsClass_UploadImageCKEditor s_params_UploadImageCKEditor = new ActionParamsClass_UploadImageCKEditor();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_UploadImageCKEditor UploadImageCKEditorParams { get { return s_params_UploadImageCKEditor; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_UploadImageCKEditor
        {
            public readonly string upload = "upload";
            public readonly string ckCsrfToken = "ckCsrfToken";
        }
        static readonly ActionParamsClass_SignOutUser s_params_SignOutUser = new ActionParamsClass_SignOutUser();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SignOutUser SignOutUserParams { get { return s_params_SignOutUser; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SignOutUser
        {
            public readonly string actionResultOverride = "actionResultOverride";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string Delete = "Delete";
                public readonly string Edit = "Edit";
                public readonly string Index = "Index";
            }
            public readonly string Delete = "~/Views/ManageVersionMessage/Delete.cshtml";
            public readonly string Edit = "~/Views/ManageVersionMessage/Edit.cshtml";
            public readonly string Index = "~/Views/ManageVersionMessage/Index.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_ManageVersionMessageController : nl.boxplosive.BackOffice.Mvc.Controllers.ManageVersionMessageController
    {
        public T4MVC_ManageVersionMessageController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void EditOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string version);

        [NonAction]
        public override System.Web.Mvc.ActionResult Edit(string version)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Edit);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "version", version);
            EditOverride(callInfo, version);
            return callInfo;
        }

        [NonAction]
        partial void EditOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, nl.boxplosive.BackOffice.Mvc.Models.ManageVersionMessage.VersionMessageModel model);

        [NonAction]
        public override System.Web.Mvc.ActionResult Edit(nl.boxplosive.BackOffice.Mvc.Models.ManageVersionMessage.VersionMessageModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Edit);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            EditOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void DeleteOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string version);

        [NonAction]
        public override System.Web.Mvc.ActionResult Delete(string version)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Delete);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "version", version);
            DeleteOverride(callInfo, version);
            return callInfo;
        }

        [NonAction]
        partial void DeleteOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, nl.boxplosive.BackOffice.Mvc.Models.ManageVersionMessage.VersionMessageModel model);

        [NonAction]
        public override System.Web.Mvc.ActionResult Delete(nl.boxplosive.BackOffice.Mvc.Models.ManageVersionMessage.VersionMessageModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Delete);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            DeleteOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void AddProductOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string gtin);

        [NonAction]
        public override System.Web.Mvc.ActionResult AddProduct(string gtin)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddProduct);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "gtin", gtin);
            AddProductOverride(callInfo, gtin);
            return callInfo;
        }

        [NonAction]
        partial void GetProductsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string term, string parentId);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetProducts(string term, string parentId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetProducts);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "term", term);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "parentId", parentId);
            GetProductsOverride(callInfo, term, parentId);
            return callInfo;
        }

        [NonAction]
        partial void GetGroupsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string term);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetGroups(string term)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetGroups);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "term", term);
            GetGroupsOverride(callInfo, term);
            return callInfo;
        }

        [NonAction]
        partial void ValidateAndSetMultiProductsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string source);

        [NonAction]
        public override System.Web.Mvc.ActionResult ValidateAndSetMultiProducts(string source)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ValidateAndSetMultiProducts);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "source", source);
            ValidateAndSetMultiProductsOverride(callInfo, source);
            return callInfo;
        }

        [NonAction]
        partial void ConfirmProductUploadOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, string source);

        [NonAction]
        public override System.Web.Mvc.JsonResult ConfirmProductUpload(string source)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.ConfirmProductUpload);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "source", source);
            ConfirmProductUploadOverride(callInfo, source);
            return callInfo;
        }

        [NonAction]
        partial void GetDownloadProductsFileResultOverride(T4MVC_System_Web_Mvc_FileContentResult callInfo, System.Collections.Generic.IList<nl.boxplosive.BackOffice.Mvc.Models.Shared.ProductModel> products, string productSetLabel);

        [NonAction]
        public override System.Web.Mvc.FileContentResult GetDownloadProductsFileResult(System.Collections.Generic.IList<nl.boxplosive.BackOffice.Mvc.Models.Shared.ProductModel> products, string productSetLabel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_FileContentResult(Area, Name, ActionNames.GetDownloadProductsFileResult);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "products", products);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "productSetLabel", productSetLabel);
            GetDownloadProductsFileResultOverride(callInfo, products, productSetLabel);
            return callInfo;
        }

        [NonAction]
        partial void GetPromotionsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string term);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetPromotions(string term)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetPromotions);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "term", term);
            GetPromotionsOverride(callInfo, term);
            return callInfo;
        }

        [NonAction]
        partial void UploadImageOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string postedFileFieldName, string urlFieldName, string urlFieldId);

        [NonAction]
        public override System.Web.Mvc.ActionResult UploadImage(string postedFileFieldName, string urlFieldName, string urlFieldId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UploadImage);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "postedFileFieldName", postedFileFieldName);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "urlFieldName", urlFieldName);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "urlFieldId", urlFieldId);
            UploadImageOverride(callInfo, postedFileFieldName, urlFieldName, urlFieldId);
            return callInfo;
        }

        [NonAction]
        partial void UploadImageCKEditorOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, System.Web.HttpPostedFileBase upload, string ckCsrfToken);

        [NonAction]
        public override System.Web.Mvc.ActionResult UploadImageCKEditor(System.Web.HttpPostedFileBase upload, string ckCsrfToken)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UploadImageCKEditor);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "upload", upload);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "ckCsrfToken", ckCsrfToken);
            UploadImageCKEditorOverride(callInfo, upload, ckCsrfToken);
            return callInfo;
        }

        [NonAction]
        partial void SignOutUserOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, System.Web.Mvc.ActionResult actionResultOverride);

        [NonAction]
        public override System.Web.Mvc.ActionResult SignOutUser(System.Web.Mvc.ActionResult actionResultOverride)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SignOutUser);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "actionResultOverride", actionResultOverride);
            SignOutUserOverride(callInfo, actionResultOverride);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
