// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace nl.boxplosive.BackOffice.Mvc.Controllers
{
    public partial class ModifyPromotionController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ModifyPromotionController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected ModifyPromotionController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Index()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Modify()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Modify);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult RemovePromotion()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.RemovePromotion);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GetStepPartial()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetStepPartial);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult SetStepBasics()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SetStepBasics);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult SetStepTimeframe()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SetStepTimeframe);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult SetStepSegmentation()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SetStepSegmentation);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult SetStepDiscount()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SetStepDiscount);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult SetStepPromotion()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SetStepPromotion);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DownloadProducts()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DownloadProducts);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.PartialViewResult GetPlaceholders()
        {
            return new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.GetPlaceholders);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult AddProduct()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddProduct);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GetProducts()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetProducts);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GetGroups()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetGroups);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ValidateAndSetMultiProducts()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ValidateAndSetMultiProducts);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult ConfirmProductUpload()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.ConfirmProductUpload);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.FileContentResult GetDownloadProductsFileResult()
        {
            return new T4MVC_System_Web_Mvc_FileContentResult(Area, Name, ActionNames.GetDownloadProductsFileResult);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GetPromotions()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetPromotions);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult UploadImage()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UploadImage);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult UploadImageCKEditor()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UploadImageCKEditor);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ModifyPromotionController Actions { get { return MVC.ModifyPromotion; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "ModifyPromotion";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "ModifyPromotion";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string Modify = "Modify";
            public readonly string Cancel = "Cancel";
            public readonly string ContinueLater = "ContinueLater";
            public readonly string Publish = "Publish";
            public readonly string RemovePromotion = "RemovePromotion";
            public readonly string GetStepPartial = "GetStepPartial";
            public readonly string GetStatusList = "GetStatusList";
            public readonly string SaveAsTemplate = "SaveAsTemplate";
            public readonly string SetStepBasics = "SetStepBasics";
            public readonly string SetStepTimeframe = "SetStepTimeframe";
            public readonly string SetStepSegmentation = "SetStepSegmentation";
            public readonly string SetStepDiscount = "SetStepDiscount";
            public readonly string SetStepPromotion = "SetStepPromotion";
            public readonly string DownloadProducts = "DownloadProducts";
            public readonly string GetPlaceholders = "GetPlaceholders";
            public readonly string AddProduct = "AddProduct";
            public readonly string GetProducts = "GetProducts";
            public readonly string GetGroups = "GetGroups";
            public readonly string ValidateAndSetMultiProducts = "ValidateAndSetMultiProducts";
            public readonly string ConfirmProductUpload = "ConfirmProductUpload";
            public readonly string GetDownloadProductsFileResult = "GetDownloadProductsFileResult";
            public readonly string GetPromotions = "GetPromotions";
            public readonly string UploadImage = "UploadImage";
            public readonly string UploadImageCKEditor = "UploadImageCKEditor";
            public readonly string SignOutUser = "SignOutUser";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string Modify = "Modify";
            public const string Cancel = "Cancel";
            public const string ContinueLater = "ContinueLater";
            public const string Publish = "Publish";
            public const string RemovePromotion = "RemovePromotion";
            public const string GetStepPartial = "GetStepPartial";
            public const string GetStatusList = "GetStatusList";
            public const string SaveAsTemplate = "SaveAsTemplate";
            public const string SetStepBasics = "SetStepBasics";
            public const string SetStepTimeframe = "SetStepTimeframe";
            public const string SetStepSegmentation = "SetStepSegmentation";
            public const string SetStepDiscount = "SetStepDiscount";
            public const string SetStepPromotion = "SetStepPromotion";
            public const string DownloadProducts = "DownloadProducts";
            public const string GetPlaceholders = "GetPlaceholders";
            public const string AddProduct = "AddProduct";
            public const string GetProducts = "GetProducts";
            public const string GetGroups = "GetGroups";
            public const string ValidateAndSetMultiProducts = "ValidateAndSetMultiProducts";
            public const string ConfirmProductUpload = "ConfirmProductUpload";
            public const string GetDownloadProductsFileResult = "GetDownloadProductsFileResult";
            public const string GetPromotions = "GetPromotions";
            public const string UploadImage = "UploadImage";
            public const string UploadImageCKEditor = "UploadImageCKEditor";
            public const string SignOutUser = "SignOutUser";
        }


        static readonly ActionParamsClass_Index s_params_Index = new ActionParamsClass_Index();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Index IndexParams { get { return s_params_Index; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Index
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_Modify s_params_Modify = new ActionParamsClass_Modify();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Modify ModifyParams { get { return s_params_Modify; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Modify
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_RemovePromotion s_params_RemovePromotion = new ActionParamsClass_RemovePromotion();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_RemovePromotion RemovePromotionParams { get { return s_params_RemovePromotion; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_RemovePromotion
        {
            public readonly string id = "id";
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_GetStepPartial s_params_GetStepPartial = new ActionParamsClass_GetStepPartial();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetStepPartial GetStepPartialParams { get { return s_params_GetStepPartial; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetStepPartial
        {
            public readonly string id = "id";
            public readonly string mode = "mode";
            public readonly string ruleIndex = "ruleIndex";
        }
        static readonly ActionParamsClass_SetStepBasics s_params_SetStepBasics = new ActionParamsClass_SetStepBasics();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SetStepBasics SetStepBasicsParams { get { return s_params_SetStepBasics; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SetStepBasics
        {
            public readonly string model = "model";
            public readonly string id = "id";
            public readonly string mode = "mode";
        }
        static readonly ActionParamsClass_SetStepTimeframe s_params_SetStepTimeframe = new ActionParamsClass_SetStepTimeframe();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SetStepTimeframe SetStepTimeframeParams { get { return s_params_SetStepTimeframe; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SetStepTimeframe
        {
            public readonly string model = "model";
            public readonly string id = "id";
            public readonly string mode = "mode";
        }
        static readonly ActionParamsClass_SetStepSegmentation s_params_SetStepSegmentation = new ActionParamsClass_SetStepSegmentation();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SetStepSegmentation SetStepSegmentationParams { get { return s_params_SetStepSegmentation; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SetStepSegmentation
        {
            public readonly string model = "model";
            public readonly string id = "id";
            public readonly string mode = "mode";
        }
        static readonly ActionParamsClass_SetStepDiscount s_params_SetStepDiscount = new ActionParamsClass_SetStepDiscount();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SetStepDiscount SetStepDiscountParams { get { return s_params_SetStepDiscount; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SetStepDiscount
        {
            public readonly string model = "model";
            public readonly string id = "id";
            public readonly string mode = "mode";
            public readonly string ruleIndex = "ruleIndex";
            public readonly string actionType = "actionType";
        }
        static readonly ActionParamsClass_SetStepPromotion s_params_SetStepPromotion = new ActionParamsClass_SetStepPromotion();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SetStepPromotion SetStepPromotionParams { get { return s_params_SetStepPromotion; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SetStepPromotion
        {
            public readonly string model = "model";
            public readonly string id = "id";
            public readonly string mode = "mode";
        }
        static readonly ActionParamsClass_DownloadProducts s_params_DownloadProducts = new ActionParamsClass_DownloadProducts();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DownloadProducts DownloadProductsParams { get { return s_params_DownloadProducts; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DownloadProducts
        {
            public readonly string selectedRuleIndex = "selectedRuleIndex";
            public readonly string stepType = "stepType";
            public readonly string productsType = "productsType";
            public readonly string fileNamePrefix = "fileNamePrefix";
        }
        static readonly ActionParamsClass_GetPlaceholders s_params_GetPlaceholders = new ActionParamsClass_GetPlaceholders();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetPlaceholders GetPlaceholdersParams { get { return s_params_GetPlaceholders; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetPlaceholders
        {
            public readonly string templateId = "templateId";
        }
        static readonly ActionParamsClass_AddProduct s_params_AddProduct = new ActionParamsClass_AddProduct();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AddProduct AddProductParams { get { return s_params_AddProduct; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AddProduct
        {
            public readonly string gtin = "gtin";
        }
        static readonly ActionParamsClass_GetProducts s_params_GetProducts = new ActionParamsClass_GetProducts();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetProducts GetProductsParams { get { return s_params_GetProducts; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetProducts
        {
            public readonly string term = "term";
            public readonly string parentId = "parentId";
        }
        static readonly ActionParamsClass_GetGroups s_params_GetGroups = new ActionParamsClass_GetGroups();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetGroups GetGroupsParams { get { return s_params_GetGroups; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetGroups
        {
            public readonly string term = "term";
        }
        static readonly ActionParamsClass_ValidateAndSetMultiProducts s_params_ValidateAndSetMultiProducts = new ActionParamsClass_ValidateAndSetMultiProducts();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ValidateAndSetMultiProducts ValidateAndSetMultiProductsParams { get { return s_params_ValidateAndSetMultiProducts; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ValidateAndSetMultiProducts
        {
            public readonly string source = "source";
        }
        static readonly ActionParamsClass_ConfirmProductUpload s_params_ConfirmProductUpload = new ActionParamsClass_ConfirmProductUpload();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ConfirmProductUpload ConfirmProductUploadParams { get { return s_params_ConfirmProductUpload; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ConfirmProductUpload
        {
            public readonly string source = "source";
        }
        static readonly ActionParamsClass_GetDownloadProductsFileResult s_params_GetDownloadProductsFileResult = new ActionParamsClass_GetDownloadProductsFileResult();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetDownloadProductsFileResult GetDownloadProductsFileResultParams { get { return s_params_GetDownloadProductsFileResult; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetDownloadProductsFileResult
        {
            public readonly string products = "products";
            public readonly string productSetLabel = "productSetLabel";
        }
        static readonly ActionParamsClass_GetPromotions s_params_GetPromotions = new ActionParamsClass_GetPromotions();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetPromotions GetPromotionsParams { get { return s_params_GetPromotions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetPromotions
        {
            public readonly string term = "term";
        }
        static readonly ActionParamsClass_UploadImage s_params_UploadImage = new ActionParamsClass_UploadImage();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_UploadImage UploadImageParams { get { return s_params_UploadImage; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_UploadImage
        {
            public readonly string postedFileFieldName = "postedFileFieldName";
            public readonly string urlFieldName = "urlFieldName";
            public readonly string urlFieldId = "urlFieldId";
        }
        static readonly ActionParamsClass_UploadImageCKEditor s_params_UploadImageCKEditor = new ActionParamsClass_UploadImageCKEditor();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_UploadImageCKEditor UploadImageCKEditorParams { get { return s_params_UploadImageCKEditor; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_UploadImageCKEditor
        {
            public readonly string upload = "upload";
            public readonly string ckCsrfToken = "ckCsrfToken";
        }
        static readonly ActionParamsClass_SignOutUser s_params_SignOutUser = new ActionParamsClass_SignOutUser();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SignOutUser SignOutUserParams { get { return s_params_SignOutUser; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SignOutUser
        {
            public readonly string actionResultOverride = "actionResultOverride";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string Index = "Index";
                public readonly string RemovePromotion = "RemovePromotion";
            }
            public readonly string Index = "~/Views/ModifyPromotion/Index.cshtml";
            public readonly string RemovePromotion = "~/Views/ModifyPromotion/RemovePromotion.cshtml";
            static readonly _DisplayTemplatesClass s_DisplayTemplates = new _DisplayTemplatesClass();
            public _DisplayTemplatesClass DisplayTemplates { get { return s_DisplayTemplates; } }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public partial class _DisplayTemplatesClass
            {
                static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
                public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
                public class _ViewNamesClass
                {
                    public readonly string BasicStepModel = "BasicStepModel";
                    public readonly string DiscountStepModel = "DiscountStepModel";
                    public readonly string PromotionStepModel = "PromotionStepModel";
                    public readonly string SegmentationStepModel = "SegmentationStepModel";
                    public readonly string StatusListModel = "StatusListModel";
                    public readonly string TimeframeStepModel = "TimeframeStepModel";
                }
                public readonly string BasicStepModel = "~/Views/ModifyPromotion/DisplayTemplates/BasicStepModel.cshtml";
                public readonly string DiscountStepModel = "~/Views/ModifyPromotion/DisplayTemplates/DiscountStepModel.cshtml";
                public readonly string PromotionStepModel = "~/Views/ModifyPromotion/DisplayTemplates/PromotionStepModel.cshtml";
                public readonly string SegmentationStepModel = "~/Views/ModifyPromotion/DisplayTemplates/SegmentationStepModel.cshtml";
                public readonly string StatusListModel = "~/Views/ModifyPromotion/DisplayTemplates/StatusListModel.cshtml";
                public readonly string TimeframeStepModel = "~/Views/ModifyPromotion/DisplayTemplates/TimeframeStepModel.cshtml";
            }
            static readonly _EditorTemplatesClass s_EditorTemplates = new _EditorTemplatesClass();
            public _EditorTemplatesClass EditorTemplates { get { return s_EditorTemplates; } }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public partial class _EditorTemplatesClass
            {
                static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
                public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
                public class _ViewNamesClass
                {
                    public readonly string Amount = "Amount";
                    public readonly string BasicStepModel = "BasicStepModel";
                    public readonly string DiscountRuleModel = "DiscountRuleModel";
                    public readonly string Enum = "Enum";
                    public readonly string PromotionStepModel = "PromotionStepModel";
                    public readonly string SegmentationStepModel = "SegmentationStepModel";
                    public readonly string TimeframeStepModel = "TimeframeStepModel";
                }
                public readonly string Amount = "~/Views/ModifyPromotion/EditorTemplates/Amount.cshtml";
                public readonly string BasicStepModel = "~/Views/ModifyPromotion/EditorTemplates/BasicStepModel.cshtml";
                public readonly string DiscountRuleModel = "~/Views/ModifyPromotion/EditorTemplates/DiscountRuleModel.cshtml";
                public readonly string Enum = "~/Views/ModifyPromotion/EditorTemplates/Enum.cshtml";
                public readonly string PromotionStepModel = "~/Views/ModifyPromotion/EditorTemplates/PromotionStepModel.cshtml";
                public readonly string SegmentationStepModel = "~/Views/ModifyPromotion/EditorTemplates/SegmentationStepModel.cshtml";
                public readonly string TimeframeStepModel = "~/Views/ModifyPromotion/EditorTemplates/TimeframeStepModel.cshtml";
            }
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_ModifyPromotionController : nl.boxplosive.BackOffice.Mvc.Controllers.ModifyPromotionController
    {
        public T4MVC_ModifyPromotionController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            IndexOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void ModifyOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string id);

        [NonAction]
        public override System.Web.Mvc.ActionResult Modify(string id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Modify);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModifyOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void CancelOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Cancel()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Cancel);
            CancelOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ContinueLaterOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult ContinueLater()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ContinueLater);
            ContinueLaterOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void PublishOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Publish()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Publish);
            PublishOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void RemovePromotionOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult RemovePromotion(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.RemovePromotion);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            RemovePromotionOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void RemovePromotionOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, nl.boxplosive.BackOffice.Mvc.Models.ModifyPromotion.ModifyPromotionModel model);

        [NonAction]
        public override System.Web.Mvc.ActionResult RemovePromotion(nl.boxplosive.BackOffice.Mvc.Models.ModifyPromotion.ModifyPromotionModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.RemovePromotion);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            RemovePromotionOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void GetStepPartialOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string id, string mode, int? ruleIndex);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetStepPartial(string id, string mode, int? ruleIndex)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetStepPartial);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "mode", mode);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "ruleIndex", ruleIndex);
            GetStepPartialOverride(callInfo, id, mode, ruleIndex);
            return callInfo;
        }

        [NonAction]
        partial void GetStatusListOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetStatusList()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetStatusList);
            GetStatusListOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void SaveAsTemplateOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult SaveAsTemplate()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SaveAsTemplate);
            SaveAsTemplateOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void SetStepBasicsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, nl.boxplosive.BackOffice.Mvc.Models.Shared.Promotion.BasicStepModel model, string id, string mode);

        [NonAction]
        public override System.Web.Mvc.ActionResult SetStepBasics(nl.boxplosive.BackOffice.Mvc.Models.Shared.Promotion.BasicStepModel model, string id, string mode)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SetStepBasics);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "mode", mode);
            SetStepBasicsOverride(callInfo, model, id, mode);
            return callInfo;
        }

        [NonAction]
        partial void SetStepTimeframeOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, nl.boxplosive.BackOffice.Mvc.Models.Shared.Promotion.PromotionTimeframeStepModel model, string id, string mode);

        [NonAction]
        public override System.Web.Mvc.ActionResult SetStepTimeframe(nl.boxplosive.BackOffice.Mvc.Models.Shared.Promotion.PromotionTimeframeStepModel model, string id, string mode)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SetStepTimeframe);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "mode", mode);
            SetStepTimeframeOverride(callInfo, model, id, mode);
            return callInfo;
        }

        [NonAction]
        partial void SetStepSegmentationOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, nl.boxplosive.BackOffice.Mvc.Models.Shared.Promotion.SegmentationStepModel model, string id, string mode);

        [NonAction]
        public override System.Web.Mvc.ActionResult SetStepSegmentation(nl.boxplosive.BackOffice.Mvc.Models.Shared.Promotion.SegmentationStepModel model, string id, string mode)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SetStepSegmentation);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "mode", mode);
            SetStepSegmentationOverride(callInfo, model, id, mode);
            return callInfo;
        }

        [NonAction]
        partial void SetStepDiscountOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, nl.boxplosive.BackOffice.Mvc.Models.Shared.Promotion.DiscountStepModel model, string id, string mode, int? ruleIndex, string actionType);

        [NonAction]
        public override System.Web.Mvc.ActionResult SetStepDiscount(nl.boxplosive.BackOffice.Mvc.Models.Shared.Promotion.DiscountStepModel model, string id, string mode, int? ruleIndex, string actionType)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SetStepDiscount);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "mode", mode);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "ruleIndex", ruleIndex);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "actionType", actionType);
            SetStepDiscountOverride(callInfo, model, id, mode, ruleIndex, actionType);
            return callInfo;
        }

        [NonAction]
        partial void SetStepPromotionOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, nl.boxplosive.BackOffice.Mvc.Models.Shared.Promotion.PromotionStepModel model, string id, string mode);

        [NonAction]
        public override System.Web.Mvc.ActionResult SetStepPromotion(nl.boxplosive.BackOffice.Mvc.Models.Shared.Promotion.PromotionStepModel model, string id, string mode)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SetStepPromotion);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "mode", mode);
            SetStepPromotionOverride(callInfo, model, id, mode);
            return callInfo;
        }

        [NonAction]
        partial void DownloadProductsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int selectedRuleIndex, nl.boxplosive.BackOffice.Mvc.Enums.StepType stepType, nl.boxplosive.BackOffice.Mvc.Enums.ProductsType productsType, string fileNamePrefix);

        [NonAction]
        public override System.Web.Mvc.ActionResult DownloadProducts(int selectedRuleIndex, nl.boxplosive.BackOffice.Mvc.Enums.StepType stepType, nl.boxplosive.BackOffice.Mvc.Enums.ProductsType productsType, string fileNamePrefix)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DownloadProducts);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "selectedRuleIndex", selectedRuleIndex);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "stepType", stepType);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "productsType", productsType);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "fileNamePrefix", fileNamePrefix);
            DownloadProductsOverride(callInfo, selectedRuleIndex, stepType, productsType, fileNamePrefix);
            return callInfo;
        }

        [NonAction]
        partial void GetPlaceholdersOverride(T4MVC_System_Web_Mvc_PartialViewResult callInfo, int? templateId);

        [NonAction]
        public override System.Web.Mvc.PartialViewResult GetPlaceholders(int? templateId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.GetPlaceholders);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "templateId", templateId);
            GetPlaceholdersOverride(callInfo, templateId);
            return callInfo;
        }

        [NonAction]
        partial void AddProductOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string gtin);

        [NonAction]
        public override System.Web.Mvc.ActionResult AddProduct(string gtin)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddProduct);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "gtin", gtin);
            AddProductOverride(callInfo, gtin);
            return callInfo;
        }

        [NonAction]
        partial void GetProductsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string term, string parentId);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetProducts(string term, string parentId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetProducts);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "term", term);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "parentId", parentId);
            GetProductsOverride(callInfo, term, parentId);
            return callInfo;
        }

        [NonAction]
        partial void GetGroupsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string term);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetGroups(string term)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetGroups);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "term", term);
            GetGroupsOverride(callInfo, term);
            return callInfo;
        }

        [NonAction]
        partial void ValidateAndSetMultiProductsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string source);

        [NonAction]
        public override System.Web.Mvc.ActionResult ValidateAndSetMultiProducts(string source)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ValidateAndSetMultiProducts);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "source", source);
            ValidateAndSetMultiProductsOverride(callInfo, source);
            return callInfo;
        }

        [NonAction]
        partial void ConfirmProductUploadOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, string source);

        [NonAction]
        public override System.Web.Mvc.JsonResult ConfirmProductUpload(string source)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.ConfirmProductUpload);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "source", source);
            ConfirmProductUploadOverride(callInfo, source);
            return callInfo;
        }

        [NonAction]
        partial void GetDownloadProductsFileResultOverride(T4MVC_System_Web_Mvc_FileContentResult callInfo, System.Collections.Generic.IList<nl.boxplosive.BackOffice.Mvc.Models.Shared.ProductModel> products, string productSetLabel);

        [NonAction]
        public override System.Web.Mvc.FileContentResult GetDownloadProductsFileResult(System.Collections.Generic.IList<nl.boxplosive.BackOffice.Mvc.Models.Shared.ProductModel> products, string productSetLabel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_FileContentResult(Area, Name, ActionNames.GetDownloadProductsFileResult);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "products", products);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "productSetLabel", productSetLabel);
            GetDownloadProductsFileResultOverride(callInfo, products, productSetLabel);
            return callInfo;
        }

        [NonAction]
        partial void GetPromotionsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string term);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetPromotions(string term)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetPromotions);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "term", term);
            GetPromotionsOverride(callInfo, term);
            return callInfo;
        }

        [NonAction]
        partial void UploadImageOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string postedFileFieldName, string urlFieldName, string urlFieldId);

        [NonAction]
        public override System.Web.Mvc.ActionResult UploadImage(string postedFileFieldName, string urlFieldName, string urlFieldId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UploadImage);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "postedFileFieldName", postedFileFieldName);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "urlFieldName", urlFieldName);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "urlFieldId", urlFieldId);
            UploadImageOverride(callInfo, postedFileFieldName, urlFieldName, urlFieldId);
            return callInfo;
        }

        [NonAction]
        partial void UploadImageCKEditorOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, System.Web.HttpPostedFileBase upload, string ckCsrfToken);

        [NonAction]
        public override System.Web.Mvc.ActionResult UploadImageCKEditor(System.Web.HttpPostedFileBase upload, string ckCsrfToken)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UploadImageCKEditor);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "upload", upload);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "ckCsrfToken", ckCsrfToken);
            UploadImageCKEditorOverride(callInfo, upload, ckCsrfToken);
            return callInfo;
        }

        [NonAction]
        partial void SignOutUserOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, System.Web.Mvc.ActionResult actionResultOverride);

        [NonAction]
        public override System.Web.Mvc.ActionResult SignOutUser(System.Web.Mvc.ActionResult actionResultOverride)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SignOutUser);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "actionResultOverride", actionResultOverride);
            SignOutUserOverride(callInfo, actionResultOverride);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
