// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace nl.boxplosive.BackOffice.Mvc.Controllers
{
    public partial class ModifyLoyaltyController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ModifyLoyaltyController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected ModifyLoyaltyController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Index()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Modify()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Modify);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Customers()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Customers);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GrantLoyaltyPoints()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GrantLoyaltyPoints);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult CustomerUpload()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.CustomerUpload);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult ConfirmCustomerUpload()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.ConfirmCustomerUpload);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.FileResult CustomerDownload()
        {
            return new T4MVC_System_Web_Mvc_FileResult(Area, Name, ActionNames.CustomerDownload);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult RemoveLoyalty()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.RemoveLoyalty);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GetStepPartial()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetStepPartial);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult SetStepBasics()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SetStepBasics);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult SetStepTimeframe()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SetStepTimeframe);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult SetStepRewards()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SetStepRewards);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult SetStepSavings()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SetStepSavings);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DownloadProducts()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DownloadProducts);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.PartialViewResult GetPlaceholders()
        {
            return new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.GetPlaceholders);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.PartialViewResult GetRewardPlaceholders()
        {
            return new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.GetRewardPlaceholders);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult AddProduct()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddProduct);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GetProducts()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetProducts);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GetGroups()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetGroups);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ValidateAndSetMultiProducts()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ValidateAndSetMultiProducts);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult ConfirmProductUpload()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.ConfirmProductUpload);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.FileContentResult GetDownloadProductsFileResult()
        {
            return new T4MVC_System_Web_Mvc_FileContentResult(Area, Name, ActionNames.GetDownloadProductsFileResult);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GetPromotions()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetPromotions);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult UploadImage()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UploadImage);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult UploadImageCKEditor()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UploadImageCKEditor);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ModifyLoyaltyController Actions { get { return MVC.ModifyLoyalty; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "ModifyLoyalty";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "ModifyLoyalty";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string Modify = "Modify";
            public readonly string Customers = "Customers";
            public readonly string GrantLoyaltyPoints = "GrantLoyaltyPoints";
            public readonly string CustomerUpload = "CustomerUpload";
            public readonly string ConfirmCustomerUpload = "ConfirmCustomerUpload";
            public readonly string CustomerDownload = "CustomerDownload";
            public readonly string Cancel = "Cancel";
            public readonly string ContinueLater = "ContinueLater";
            public readonly string Publish = "Publish";
            public readonly string RemoveLoyalty = "RemoveLoyalty";
            public readonly string GetStatusList = "GetStatusList";
            public readonly string UploadImageRewardRule = "UploadImageRewardRule";
            public readonly string GetStepPartial = "GetStepPartial";
            public readonly string SetStepBasics = "SetStepBasics";
            public readonly string SetStepTimeframe = "SetStepTimeframe";
            public readonly string SetStepRewards = "SetStepRewards";
            public readonly string SetStepSavings = "SetStepSavings";
            public readonly string DownloadProducts = "DownloadProducts";
            public readonly string GetPlaceholders = "GetPlaceholders";
            public readonly string GetRewardPlaceholders = "GetRewardPlaceholders";
            public readonly string AddProduct = "AddProduct";
            public readonly string GetProducts = "GetProducts";
            public readonly string GetGroups = "GetGroups";
            public readonly string ValidateAndSetMultiProducts = "ValidateAndSetMultiProducts";
            public readonly string ConfirmProductUpload = "ConfirmProductUpload";
            public readonly string GetDownloadProductsFileResult = "GetDownloadProductsFileResult";
            public readonly string GetPromotions = "GetPromotions";
            public readonly string UploadImage = "UploadImage";
            public readonly string UploadImageCKEditor = "UploadImageCKEditor";
            public readonly string SignOutUser = "SignOutUser";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string Modify = "Modify";
            public const string Customers = "Customers";
            public const string GrantLoyaltyPoints = "GrantLoyaltyPoints";
            public const string CustomerUpload = "CustomerUpload";
            public const string ConfirmCustomerUpload = "ConfirmCustomerUpload";
            public const string CustomerDownload = "CustomerDownload";
            public const string Cancel = "Cancel";
            public const string ContinueLater = "ContinueLater";
            public const string Publish = "Publish";
            public const string RemoveLoyalty = "RemoveLoyalty";
            public const string GetStatusList = "GetStatusList";
            public const string UploadImageRewardRule = "UploadImageRewardRule";
            public const string GetStepPartial = "GetStepPartial";
            public const string SetStepBasics = "SetStepBasics";
            public const string SetStepTimeframe = "SetStepTimeframe";
            public const string SetStepRewards = "SetStepRewards";
            public const string SetStepSavings = "SetStepSavings";
            public const string DownloadProducts = "DownloadProducts";
            public const string GetPlaceholders = "GetPlaceholders";
            public const string GetRewardPlaceholders = "GetRewardPlaceholders";
            public const string AddProduct = "AddProduct";
            public const string GetProducts = "GetProducts";
            public const string GetGroups = "GetGroups";
            public const string ValidateAndSetMultiProducts = "ValidateAndSetMultiProducts";
            public const string ConfirmProductUpload = "ConfirmProductUpload";
            public const string GetDownloadProductsFileResult = "GetDownloadProductsFileResult";
            public const string GetPromotions = "GetPromotions";
            public const string UploadImage = "UploadImage";
            public const string UploadImageCKEditor = "UploadImageCKEditor";
            public const string SignOutUser = "SignOutUser";
        }


        static readonly ActionParamsClass_Index s_params_Index = new ActionParamsClass_Index();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Index IndexParams { get { return s_params_Index; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Index
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_Modify s_params_Modify = new ActionParamsClass_Modify();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Modify ModifyParams { get { return s_params_Modify; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Modify
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_Customers s_params_Customers = new ActionParamsClass_Customers();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Customers CustomersParams { get { return s_params_Customers; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Customers
        {
            public readonly string loyaltyProgramId = "id";
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_GrantLoyaltyPoints s_params_GrantLoyaltyPoints = new ActionParamsClass_GrantLoyaltyPoints();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GrantLoyaltyPoints GrantLoyaltyPointsParams { get { return s_params_GrantLoyaltyPoints; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GrantLoyaltyPoints
        {
            public readonly string loyaltyProgramId = "id";
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_CustomerUpload s_params_CustomerUpload = new ActionParamsClass_CustomerUpload();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_CustomerUpload CustomerUploadParams { get { return s_params_CustomerUpload; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_CustomerUpload
        {
            public readonly string loyaltyProgramId = "id";
        }
        static readonly ActionParamsClass_ConfirmCustomerUpload s_params_ConfirmCustomerUpload = new ActionParamsClass_ConfirmCustomerUpload();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ConfirmCustomerUpload ConfirmCustomerUploadParams { get { return s_params_ConfirmCustomerUpload; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ConfirmCustomerUpload
        {
            public readonly string loyaltyProgramId = "id";
        }
        static readonly ActionParamsClass_CustomerDownload s_params_CustomerDownload = new ActionParamsClass_CustomerDownload();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_CustomerDownload CustomerDownloadParams { get { return s_params_CustomerDownload; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_CustomerDownload
        {
            public readonly string loyaltyProgramId = "id";
        }
        static readonly ActionParamsClass_RemoveLoyalty s_params_RemoveLoyalty = new ActionParamsClass_RemoveLoyalty();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_RemoveLoyalty RemoveLoyaltyParams { get { return s_params_RemoveLoyalty; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_RemoveLoyalty
        {
            public readonly string id = "id";
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_GetStepPartial s_params_GetStepPartial = new ActionParamsClass_GetStepPartial();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetStepPartial GetStepPartialParams { get { return s_params_GetStepPartial; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetStepPartial
        {
            public readonly string id = "id";
            public readonly string mode = "mode";
            public readonly string ruleIndex = "ruleIndex";
        }
        static readonly ActionParamsClass_SetStepBasics s_params_SetStepBasics = new ActionParamsClass_SetStepBasics();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SetStepBasics SetStepBasicsParams { get { return s_params_SetStepBasics; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SetStepBasics
        {
            public readonly string model = "model";
            public readonly string id = "id";
            public readonly string mode = "mode";
        }
        static readonly ActionParamsClass_SetStepTimeframe s_params_SetStepTimeframe = new ActionParamsClass_SetStepTimeframe();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SetStepTimeframe SetStepTimeframeParams { get { return s_params_SetStepTimeframe; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SetStepTimeframe
        {
            public readonly string model = "model";
            public readonly string id = "id";
            public readonly string mode = "mode";
        }
        static readonly ActionParamsClass_SetStepRewards s_params_SetStepRewards = new ActionParamsClass_SetStepRewards();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SetStepRewards SetStepRewardsParams { get { return s_params_SetStepRewards; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SetStepRewards
        {
            public readonly string model = "model";
            public readonly string id = "id";
            public readonly string mode = "mode";
            public readonly string ruleIndex = "ruleIndex";
            public readonly string actionType = "actionType";
        }
        static readonly ActionParamsClass_SetStepSavings s_params_SetStepSavings = new ActionParamsClass_SetStepSavings();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SetStepSavings SetStepSavingsParams { get { return s_params_SetStepSavings; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SetStepSavings
        {
            public readonly string model = "model";
            public readonly string id = "id";
            public readonly string mode = "mode";
            public readonly string ruleIndex = "ruleIndex";
            public readonly string actionType = "actionType";
        }
        static readonly ActionParamsClass_DownloadProducts s_params_DownloadProducts = new ActionParamsClass_DownloadProducts();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DownloadProducts DownloadProductsParams { get { return s_params_DownloadProducts; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DownloadProducts
        {
            public readonly string selectedRuleIndex = "selectedRuleIndex";
            public readonly string stepType = "stepType";
            public readonly string productsType = "productsType";
            public readonly string fileNamePrefix = "fileNamePrefix";
        }
        static readonly ActionParamsClass_GetPlaceholders s_params_GetPlaceholders = new ActionParamsClass_GetPlaceholders();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetPlaceholders GetPlaceholdersParams { get { return s_params_GetPlaceholders; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetPlaceholders
        {
            public readonly string templateId = "templateId";
        }
        static readonly ActionParamsClass_GetRewardPlaceholders s_params_GetRewardPlaceholders = new ActionParamsClass_GetRewardPlaceholders();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetRewardPlaceholders GetRewardPlaceholdersParams { get { return s_params_GetRewardPlaceholders; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetRewardPlaceholders
        {
            public readonly string templateId = "templateId";
            public readonly string rewardRuleIndex = "rewardRuleIndex";
        }
        static readonly ActionParamsClass_AddProduct s_params_AddProduct = new ActionParamsClass_AddProduct();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AddProduct AddProductParams { get { return s_params_AddProduct; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AddProduct
        {
            public readonly string gtin = "gtin";
        }
        static readonly ActionParamsClass_GetProducts s_params_GetProducts = new ActionParamsClass_GetProducts();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetProducts GetProductsParams { get { return s_params_GetProducts; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetProducts
        {
            public readonly string term = "term";
            public readonly string parentId = "parentId";
        }
        static readonly ActionParamsClass_GetGroups s_params_GetGroups = new ActionParamsClass_GetGroups();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetGroups GetGroupsParams { get { return s_params_GetGroups; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetGroups
        {
            public readonly string term = "term";
        }
        static readonly ActionParamsClass_ValidateAndSetMultiProducts s_params_ValidateAndSetMultiProducts = new ActionParamsClass_ValidateAndSetMultiProducts();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ValidateAndSetMultiProducts ValidateAndSetMultiProductsParams { get { return s_params_ValidateAndSetMultiProducts; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ValidateAndSetMultiProducts
        {
            public readonly string source = "source";
        }
        static readonly ActionParamsClass_ConfirmProductUpload s_params_ConfirmProductUpload = new ActionParamsClass_ConfirmProductUpload();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ConfirmProductUpload ConfirmProductUploadParams { get { return s_params_ConfirmProductUpload; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ConfirmProductUpload
        {
            public readonly string source = "source";
        }
        static readonly ActionParamsClass_GetDownloadProductsFileResult s_params_GetDownloadProductsFileResult = new ActionParamsClass_GetDownloadProductsFileResult();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetDownloadProductsFileResult GetDownloadProductsFileResultParams { get { return s_params_GetDownloadProductsFileResult; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetDownloadProductsFileResult
        {
            public readonly string products = "products";
            public readonly string productSetLabel = "productSetLabel";
        }
        static readonly ActionParamsClass_GetPromotions s_params_GetPromotions = new ActionParamsClass_GetPromotions();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetPromotions GetPromotionsParams { get { return s_params_GetPromotions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetPromotions
        {
            public readonly string term = "term";
        }
        static readonly ActionParamsClass_UploadImage s_params_UploadImage = new ActionParamsClass_UploadImage();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_UploadImage UploadImageParams { get { return s_params_UploadImage; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_UploadImage
        {
            public readonly string postedFileFieldName = "postedFileFieldName";
            public readonly string urlFieldName = "urlFieldName";
            public readonly string urlFieldId = "urlFieldId";
        }
        static readonly ActionParamsClass_UploadImageCKEditor s_params_UploadImageCKEditor = new ActionParamsClass_UploadImageCKEditor();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_UploadImageCKEditor UploadImageCKEditorParams { get { return s_params_UploadImageCKEditor; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_UploadImageCKEditor
        {
            public readonly string upload = "upload";
            public readonly string ckCsrfToken = "ckCsrfToken";
        }
        static readonly ActionParamsClass_SignOutUser s_params_SignOutUser = new ActionParamsClass_SignOutUser();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SignOutUser SignOutUserParams { get { return s_params_SignOutUser; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SignOutUser
        {
            public readonly string actionResultOverride = "actionResultOverride";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string Customers = "Customers";
                public readonly string GrantLoyaltyPoints = "GrantLoyaltyPoints";
                public readonly string Index = "Index";
                public readonly string RemoveLoyalty = "RemoveLoyalty";
            }
            public readonly string Customers = "~/Views/ModifyLoyalty/Customers.cshtml";
            public readonly string GrantLoyaltyPoints = "~/Views/ModifyLoyalty/GrantLoyaltyPoints.cshtml";
            public readonly string Index = "~/Views/ModifyLoyalty/Index.cshtml";
            public readonly string RemoveLoyalty = "~/Views/ModifyLoyalty/RemoveLoyalty.cshtml";
            static readonly _DisplayTemplatesClass s_DisplayTemplates = new _DisplayTemplatesClass();
            public _DisplayTemplatesClass DisplayTemplates { get { return s_DisplayTemplates; } }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public partial class _DisplayTemplatesClass
            {
                static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
                public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
                public class _ViewNamesClass
                {
                    public readonly string BasicStepModel = "BasicStepModel";
                    public readonly string ModifyStatusListModel = "ModifyStatusListModel";
                    public readonly string RewardsStepModel = "RewardsStepModel";
                    public readonly string SavingsStepModel = "SavingsStepModel";
                    public readonly string TimeframeStepModel = "TimeframeStepModel";
                }
                public readonly string BasicStepModel = "~/Views/ModifyLoyalty/DisplayTemplates/BasicStepModel.cshtml";
                public readonly string ModifyStatusListModel = "~/Views/ModifyLoyalty/DisplayTemplates/ModifyStatusListModel.cshtml";
                public readonly string RewardsStepModel = "~/Views/ModifyLoyalty/DisplayTemplates/RewardsStepModel.cshtml";
                public readonly string SavingsStepModel = "~/Views/ModifyLoyalty/DisplayTemplates/SavingsStepModel.cshtml";
                public readonly string TimeframeStepModel = "~/Views/ModifyLoyalty/DisplayTemplates/TimeframeStepModel.cshtml";
            }
            static readonly _EditorTemplatesClass s_EditorTemplates = new _EditorTemplatesClass();
            public _EditorTemplatesClass EditorTemplates { get { return s_EditorTemplates; } }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public partial class _EditorTemplatesClass
            {
                static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
                public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
                public class _ViewNamesClass
                {
                    public readonly string BasicStepModel = "BasicStepModel";
                    public readonly string RewardsRuleModel = "RewardsRuleModel";
                    public readonly string RewardsStepModel = "RewardsStepModel";
                    public readonly string SavingsStepModel = "SavingsStepModel";
                    public readonly string TimeframeStepModel = "TimeframeStepModel";
                }
                public readonly string BasicStepModel = "~/Views/ModifyLoyalty/EditorTemplates/BasicStepModel.cshtml";
                public readonly string RewardsRuleModel = "~/Views/ModifyLoyalty/EditorTemplates/RewardsRuleModel.cshtml";
                public readonly string RewardsStepModel = "~/Views/ModifyLoyalty/EditorTemplates/RewardsStepModel.cshtml";
                public readonly string SavingsStepModel = "~/Views/ModifyLoyalty/EditorTemplates/SavingsStepModel.cshtml";
                public readonly string TimeframeStepModel = "~/Views/ModifyLoyalty/EditorTemplates/TimeframeStepModel.cshtml";
            }
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_ModifyLoyaltyController : nl.boxplosive.BackOffice.Mvc.Controllers.ModifyLoyaltyController
    {
        public T4MVC_ModifyLoyaltyController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            IndexOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void ModifyOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult Modify(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Modify);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModifyOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void CustomersOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int loyaltyProgramId);

        [NonAction]
        public override System.Web.Mvc.ActionResult Customers(int loyaltyProgramId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Customers);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", loyaltyProgramId);
            CustomersOverride(callInfo, loyaltyProgramId);
            return callInfo;
        }

        [NonAction]
        partial void CustomersOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, nl.boxplosive.BackOffice.Mvc.Models.ModifyLoyalty.ModifyLoyaltyCustomersModel model);

        [NonAction]
        public override System.Web.Mvc.ActionResult Customers(nl.boxplosive.BackOffice.Mvc.Models.ModifyLoyalty.ModifyLoyaltyCustomersModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Customers);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            CustomersOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void GrantLoyaltyPointsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int loyaltyProgramId);

        [NonAction]
        public override System.Web.Mvc.ActionResult GrantLoyaltyPoints(int loyaltyProgramId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GrantLoyaltyPoints);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", loyaltyProgramId);
            GrantLoyaltyPointsOverride(callInfo, loyaltyProgramId);
            return callInfo;
        }

        [NonAction]
        partial void GrantLoyaltyPointsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, nl.boxplosive.BackOffice.Mvc.Models.ModifyLoyalty.ModifyLoyaltyGrantLoyaltyPointsModel model);

        [NonAction]
        public override System.Web.Mvc.ActionResult GrantLoyaltyPoints(nl.boxplosive.BackOffice.Mvc.Models.ModifyLoyalty.ModifyLoyaltyGrantLoyaltyPointsModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GrantLoyaltyPoints);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            GrantLoyaltyPointsOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void CustomerUploadOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, int loyaltyProgramId);

        [NonAction]
        public override System.Web.Mvc.JsonResult CustomerUpload(int loyaltyProgramId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.CustomerUpload);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", loyaltyProgramId);
            CustomerUploadOverride(callInfo, loyaltyProgramId);
            return callInfo;
        }

        [NonAction]
        partial void ConfirmCustomerUploadOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, int loyaltyProgramId);

        [NonAction]
        public override System.Web.Mvc.JsonResult ConfirmCustomerUpload(int loyaltyProgramId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.ConfirmCustomerUpload);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", loyaltyProgramId);
            ConfirmCustomerUploadOverride(callInfo, loyaltyProgramId);
            return callInfo;
        }

        [NonAction]
        partial void CustomerDownloadOverride(T4MVC_System_Web_Mvc_FileResult callInfo, int loyaltyProgramId);

        [NonAction]
        public override System.Web.Mvc.FileResult CustomerDownload(int loyaltyProgramId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_FileResult(Area, Name, ActionNames.CustomerDownload);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", loyaltyProgramId);
            CustomerDownloadOverride(callInfo, loyaltyProgramId);
            return callInfo;
        }

        [NonAction]
        partial void CancelOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Cancel()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Cancel);
            CancelOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ContinueLaterOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult ContinueLater()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ContinueLater);
            ContinueLaterOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void PublishOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Publish()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Publish);
            PublishOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void RemoveLoyaltyOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult RemoveLoyalty(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.RemoveLoyalty);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            RemoveLoyaltyOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void RemoveLoyaltyOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, nl.boxplosive.BackOffice.Mvc.Models.ModifyLoyalty.ModifyLoyaltyModel model);

        [NonAction]
        public override System.Web.Mvc.ActionResult RemoveLoyalty(nl.boxplosive.BackOffice.Mvc.Models.ModifyLoyalty.ModifyLoyaltyModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.RemoveLoyalty);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            RemoveLoyaltyOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void GetStatusListOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetStatusList()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetStatusList);
            GetStatusListOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void UploadImageRewardRuleOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult UploadImageRewardRule()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UploadImageRewardRule);
            UploadImageRewardRuleOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void GetStepPartialOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string id, string mode, int? ruleIndex);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetStepPartial(string id, string mode, int? ruleIndex)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetStepPartial);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "mode", mode);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "ruleIndex", ruleIndex);
            GetStepPartialOverride(callInfo, id, mode, ruleIndex);
            return callInfo;
        }

        [NonAction]
        partial void SetStepBasicsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, nl.boxplosive.BackOffice.Mvc.Models.Shared.Loyalty.BasicStepModel model, string id, string mode);

        [NonAction]
        public override System.Web.Mvc.ActionResult SetStepBasics(nl.boxplosive.BackOffice.Mvc.Models.Shared.Loyalty.BasicStepModel model, string id, string mode)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SetStepBasics);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "mode", mode);
            SetStepBasicsOverride(callInfo, model, id, mode);
            return callInfo;
        }

        [NonAction]
        partial void SetStepTimeframeOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, nl.boxplosive.BackOffice.Mvc.Models.Shared.TimeframeStepModel model, string id, string mode);

        [NonAction]
        public override System.Web.Mvc.ActionResult SetStepTimeframe(nl.boxplosive.BackOffice.Mvc.Models.Shared.TimeframeStepModel model, string id, string mode)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SetStepTimeframe);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "mode", mode);
            SetStepTimeframeOverride(callInfo, model, id, mode);
            return callInfo;
        }

        [NonAction]
        partial void SetStepRewardsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, nl.boxplosive.BackOffice.Mvc.Models.Shared.Loyalty.RewardsStepModel model, string id, string mode, int? ruleIndex, string actionType);

        [NonAction]
        public override System.Web.Mvc.ActionResult SetStepRewards(nl.boxplosive.BackOffice.Mvc.Models.Shared.Loyalty.RewardsStepModel model, string id, string mode, int? ruleIndex, string actionType)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SetStepRewards);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "mode", mode);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "ruleIndex", ruleIndex);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "actionType", actionType);
            SetStepRewardsOverride(callInfo, model, id, mode, ruleIndex, actionType);
            return callInfo;
        }

        [NonAction]
        partial void SetStepSavingsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, nl.boxplosive.BackOffice.Mvc.Models.Shared.Loyalty.SavingsStepModel model, string id, string mode, int? ruleIndex, string actionType);

        [NonAction]
        public override System.Web.Mvc.ActionResult SetStepSavings(nl.boxplosive.BackOffice.Mvc.Models.Shared.Loyalty.SavingsStepModel model, string id, string mode, int? ruleIndex, string actionType)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SetStepSavings);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "mode", mode);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "ruleIndex", ruleIndex);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "actionType", actionType);
            SetStepSavingsOverride(callInfo, model, id, mode, ruleIndex, actionType);
            return callInfo;
        }

        [NonAction]
        partial void DownloadProductsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int selectedRuleIndex, nl.boxplosive.BackOffice.Mvc.Enums.StepType stepType, nl.boxplosive.BackOffice.Mvc.Enums.ProductsType productsType, string fileNamePrefix);

        [NonAction]
        public override System.Web.Mvc.ActionResult DownloadProducts(int selectedRuleIndex, nl.boxplosive.BackOffice.Mvc.Enums.StepType stepType, nl.boxplosive.BackOffice.Mvc.Enums.ProductsType productsType, string fileNamePrefix)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DownloadProducts);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "selectedRuleIndex", selectedRuleIndex);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "stepType", stepType);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "productsType", productsType);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "fileNamePrefix", fileNamePrefix);
            DownloadProductsOverride(callInfo, selectedRuleIndex, stepType, productsType, fileNamePrefix);
            return callInfo;
        }

        [NonAction]
        partial void GetPlaceholdersOverride(T4MVC_System_Web_Mvc_PartialViewResult callInfo, int? templateId);

        [NonAction]
        public override System.Web.Mvc.PartialViewResult GetPlaceholders(int? templateId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.GetPlaceholders);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "templateId", templateId);
            GetPlaceholdersOverride(callInfo, templateId);
            return callInfo;
        }

        [NonAction]
        partial void GetRewardPlaceholdersOverride(T4MVC_System_Web_Mvc_PartialViewResult callInfo, int? templateId, int? rewardRuleIndex);

        [NonAction]
        public override System.Web.Mvc.PartialViewResult GetRewardPlaceholders(int? templateId, int? rewardRuleIndex)
        {
            var callInfo = new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.GetRewardPlaceholders);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "templateId", templateId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "rewardRuleIndex", rewardRuleIndex);
            GetRewardPlaceholdersOverride(callInfo, templateId, rewardRuleIndex);
            return callInfo;
        }

        [NonAction]
        partial void AddProductOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string gtin);

        [NonAction]
        public override System.Web.Mvc.ActionResult AddProduct(string gtin)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddProduct);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "gtin", gtin);
            AddProductOverride(callInfo, gtin);
            return callInfo;
        }

        [NonAction]
        partial void GetProductsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string term, string parentId);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetProducts(string term, string parentId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetProducts);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "term", term);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "parentId", parentId);
            GetProductsOverride(callInfo, term, parentId);
            return callInfo;
        }

        [NonAction]
        partial void GetGroupsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string term);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetGroups(string term)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetGroups);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "term", term);
            GetGroupsOverride(callInfo, term);
            return callInfo;
        }

        [NonAction]
        partial void ValidateAndSetMultiProductsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string source);

        [NonAction]
        public override System.Web.Mvc.ActionResult ValidateAndSetMultiProducts(string source)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ValidateAndSetMultiProducts);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "source", source);
            ValidateAndSetMultiProductsOverride(callInfo, source);
            return callInfo;
        }

        [NonAction]
        partial void ConfirmProductUploadOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, string source);

        [NonAction]
        public override System.Web.Mvc.JsonResult ConfirmProductUpload(string source)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.ConfirmProductUpload);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "source", source);
            ConfirmProductUploadOverride(callInfo, source);
            return callInfo;
        }

        [NonAction]
        partial void GetDownloadProductsFileResultOverride(T4MVC_System_Web_Mvc_FileContentResult callInfo, System.Collections.Generic.IList<nl.boxplosive.BackOffice.Mvc.Models.Shared.ProductModel> products, string productSetLabel);

        [NonAction]
        public override System.Web.Mvc.FileContentResult GetDownloadProductsFileResult(System.Collections.Generic.IList<nl.boxplosive.BackOffice.Mvc.Models.Shared.ProductModel> products, string productSetLabel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_FileContentResult(Area, Name, ActionNames.GetDownloadProductsFileResult);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "products", products);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "productSetLabel", productSetLabel);
            GetDownloadProductsFileResultOverride(callInfo, products, productSetLabel);
            return callInfo;
        }

        [NonAction]
        partial void GetPromotionsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string term);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetPromotions(string term)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetPromotions);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "term", term);
            GetPromotionsOverride(callInfo, term);
            return callInfo;
        }

        [NonAction]
        partial void UploadImageOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string postedFileFieldName, string urlFieldName, string urlFieldId);

        [NonAction]
        public override System.Web.Mvc.ActionResult UploadImage(string postedFileFieldName, string urlFieldName, string urlFieldId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UploadImage);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "postedFileFieldName", postedFileFieldName);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "urlFieldName", urlFieldName);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "urlFieldId", urlFieldId);
            UploadImageOverride(callInfo, postedFileFieldName, urlFieldName, urlFieldId);
            return callInfo;
        }

        [NonAction]
        partial void UploadImageCKEditorOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, System.Web.HttpPostedFileBase upload, string ckCsrfToken);

        [NonAction]
        public override System.Web.Mvc.ActionResult UploadImageCKEditor(System.Web.HttpPostedFileBase upload, string ckCsrfToken)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UploadImageCKEditor);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "upload", upload);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "ckCsrfToken", ckCsrfToken);
            UploadImageCKEditorOverride(callInfo, upload, ckCsrfToken);
            return callInfo;
        }

        [NonAction]
        partial void SignOutUserOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, System.Web.Mvc.ActionResult actionResultOverride);

        [NonAction]
        public override System.Web.Mvc.ActionResult SignOutUser(System.Web.Mvc.ActionResult actionResultOverride)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SignOutUser);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "actionResultOverride", actionResultOverride);
            SignOutUserOverride(callInfo, actionResultOverride);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
