// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace nl.boxplosive.BackOffice.Mvc.Controllers
{
    public partial class PublishLoyaltyController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public PublishLoyaltyController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected PublishLoyaltyController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ReadyToPublish()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ReadyToPublish);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Edit()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Edit);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Publish()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Publish);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DownloadProducts()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DownloadProducts);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.PartialViewResult GetPlaceholders()
        {
            return new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.GetPlaceholders);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.PartialViewResult GetRewardPlaceholders()
        {
            return new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.GetRewardPlaceholders);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult AddProduct()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddProduct);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GetProducts()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetProducts);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GetGroups()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetGroups);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ValidateAndSetMultiProducts()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ValidateAndSetMultiProducts);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult ConfirmProductUpload()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.ConfirmProductUpload);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.FileContentResult GetDownloadProductsFileResult()
        {
            return new T4MVC_System_Web_Mvc_FileContentResult(Area, Name, ActionNames.GetDownloadProductsFileResult);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GetPromotions()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetPromotions);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult UploadImage()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UploadImage);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult UploadImageCKEditor()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UploadImageCKEditor);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public PublishLoyaltyController Actions { get { return MVC.PublishLoyalty; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "PublishLoyalty";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "PublishLoyalty";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string ReadyToPublish = "ReadyToPublish";
            public readonly string Edit = "Edit";
            public readonly string Publish = "Publish";
            public readonly string DownloadProducts = "DownloadProducts";
            public readonly string GetPlaceholders = "GetPlaceholders";
            public readonly string GetRewardPlaceholders = "GetRewardPlaceholders";
            public readonly string AddProduct = "AddProduct";
            public readonly string GetProducts = "GetProducts";
            public readonly string GetGroups = "GetGroups";
            public readonly string ValidateAndSetMultiProducts = "ValidateAndSetMultiProducts";
            public readonly string ConfirmProductUpload = "ConfirmProductUpload";
            public readonly string GetDownloadProductsFileResult = "GetDownloadProductsFileResult";
            public readonly string GetPromotions = "GetPromotions";
            public readonly string UploadImage = "UploadImage";
            public readonly string UploadImageCKEditor = "UploadImageCKEditor";
            public readonly string SignOutUser = "SignOutUser";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string ReadyToPublish = "ReadyToPublish";
            public const string Edit = "Edit";
            public const string Publish = "Publish";
            public const string DownloadProducts = "DownloadProducts";
            public const string GetPlaceholders = "GetPlaceholders";
            public const string GetRewardPlaceholders = "GetRewardPlaceholders";
            public const string AddProduct = "AddProduct";
            public const string GetProducts = "GetProducts";
            public const string GetGroups = "GetGroups";
            public const string ValidateAndSetMultiProducts = "ValidateAndSetMultiProducts";
            public const string ConfirmProductUpload = "ConfirmProductUpload";
            public const string GetDownloadProductsFileResult = "GetDownloadProductsFileResult";
            public const string GetPromotions = "GetPromotions";
            public const string UploadImage = "UploadImage";
            public const string UploadImageCKEditor = "UploadImageCKEditor";
            public const string SignOutUser = "SignOutUser";
        }


        static readonly ActionParamsClass_ReadyToPublish s_params_ReadyToPublish = new ActionParamsClass_ReadyToPublish();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ReadyToPublish ReadyToPublishParams { get { return s_params_ReadyToPublish; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ReadyToPublish
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_Edit s_params_Edit = new ActionParamsClass_Edit();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Edit EditParams { get { return s_params_Edit; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Edit
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_Publish s_params_Publish = new ActionParamsClass_Publish();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Publish PublishParams { get { return s_params_Publish; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Publish
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_DownloadProducts s_params_DownloadProducts = new ActionParamsClass_DownloadProducts();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DownloadProducts DownloadProductsParams { get { return s_params_DownloadProducts; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DownloadProducts
        {
            public readonly string selectedRuleIndex = "selectedRuleIndex";
            public readonly string stepType = "stepType";
            public readonly string productsType = "productsType";
            public readonly string fileNamePrefix = "fileNamePrefix";
        }
        static readonly ActionParamsClass_GetPlaceholders s_params_GetPlaceholders = new ActionParamsClass_GetPlaceholders();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetPlaceholders GetPlaceholdersParams { get { return s_params_GetPlaceholders; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetPlaceholders
        {
            public readonly string templateId = "templateId";
        }
        static readonly ActionParamsClass_GetRewardPlaceholders s_params_GetRewardPlaceholders = new ActionParamsClass_GetRewardPlaceholders();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetRewardPlaceholders GetRewardPlaceholdersParams { get { return s_params_GetRewardPlaceholders; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetRewardPlaceholders
        {
            public readonly string templateId = "templateId";
            public readonly string rewardRuleIndex = "rewardRuleIndex";
        }
        static readonly ActionParamsClass_AddProduct s_params_AddProduct = new ActionParamsClass_AddProduct();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AddProduct AddProductParams { get { return s_params_AddProduct; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AddProduct
        {
            public readonly string gtin = "gtin";
        }
        static readonly ActionParamsClass_GetProducts s_params_GetProducts = new ActionParamsClass_GetProducts();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetProducts GetProductsParams { get { return s_params_GetProducts; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetProducts
        {
            public readonly string term = "term";
            public readonly string parentId = "parentId";
        }
        static readonly ActionParamsClass_GetGroups s_params_GetGroups = new ActionParamsClass_GetGroups();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetGroups GetGroupsParams { get { return s_params_GetGroups; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetGroups
        {
            public readonly string term = "term";
        }
        static readonly ActionParamsClass_ValidateAndSetMultiProducts s_params_ValidateAndSetMultiProducts = new ActionParamsClass_ValidateAndSetMultiProducts();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ValidateAndSetMultiProducts ValidateAndSetMultiProductsParams { get { return s_params_ValidateAndSetMultiProducts; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ValidateAndSetMultiProducts
        {
            public readonly string source = "source";
        }
        static readonly ActionParamsClass_ConfirmProductUpload s_params_ConfirmProductUpload = new ActionParamsClass_ConfirmProductUpload();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ConfirmProductUpload ConfirmProductUploadParams { get { return s_params_ConfirmProductUpload; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ConfirmProductUpload
        {
            public readonly string source = "source";
        }
        static readonly ActionParamsClass_GetDownloadProductsFileResult s_params_GetDownloadProductsFileResult = new ActionParamsClass_GetDownloadProductsFileResult();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetDownloadProductsFileResult GetDownloadProductsFileResultParams { get { return s_params_GetDownloadProductsFileResult; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetDownloadProductsFileResult
        {
            public readonly string products = "products";
            public readonly string productSetLabel = "productSetLabel";
        }
        static readonly ActionParamsClass_GetPromotions s_params_GetPromotions = new ActionParamsClass_GetPromotions();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetPromotions GetPromotionsParams { get { return s_params_GetPromotions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetPromotions
        {
            public readonly string term = "term";
        }
        static readonly ActionParamsClass_UploadImage s_params_UploadImage = new ActionParamsClass_UploadImage();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_UploadImage UploadImageParams { get { return s_params_UploadImage; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_UploadImage
        {
            public readonly string postedFileFieldName = "postedFileFieldName";
            public readonly string urlFieldName = "urlFieldName";
            public readonly string urlFieldId = "urlFieldId";
        }
        static readonly ActionParamsClass_UploadImageCKEditor s_params_UploadImageCKEditor = new ActionParamsClass_UploadImageCKEditor();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_UploadImageCKEditor UploadImageCKEditorParams { get { return s_params_UploadImageCKEditor; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_UploadImageCKEditor
        {
            public readonly string upload = "upload";
            public readonly string ckCsrfToken = "ckCsrfToken";
        }
        static readonly ActionParamsClass_SignOutUser s_params_SignOutUser = new ActionParamsClass_SignOutUser();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SignOutUser SignOutUserParams { get { return s_params_SignOutUser; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SignOutUser
        {
            public readonly string actionResultOverride = "actionResultOverride";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string ReadyToPublish = "ReadyToPublish";
            }
            public readonly string ReadyToPublish = "~/Views/PublishLoyalty/ReadyToPublish.cshtml";
            static readonly _DisplayTemplatesClass s_DisplayTemplates = new _DisplayTemplatesClass();
            public _DisplayTemplatesClass DisplayTemplates { get { return s_DisplayTemplates; } }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public partial class _DisplayTemplatesClass
            {
                static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
                public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
                public class _ViewNamesClass
                {
                    public readonly string BasicStepModel = "BasicStepModel";
                    public readonly string RewardsStepModel = "RewardsStepModel";
                    public readonly string SavingsStepModel = "SavingsStepModel";
                    public readonly string TimeframeStepModel = "TimeframeStepModel";
                }
                public readonly string BasicStepModel = "~/Views/PublishLoyalty/DisplayTemplates/BasicStepModel.cshtml";
                public readonly string RewardsStepModel = "~/Views/PublishLoyalty/DisplayTemplates/RewardsStepModel.cshtml";
                public readonly string SavingsStepModel = "~/Views/PublishLoyalty/DisplayTemplates/SavingsStepModel.cshtml";
                public readonly string TimeframeStepModel = "~/Views/PublishLoyalty/DisplayTemplates/TimeframeStepModel.cshtml";
            }
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_PublishLoyaltyController : nl.boxplosive.BackOffice.Mvc.Controllers.PublishLoyaltyController
    {
        public T4MVC_PublishLoyaltyController() : base(Dummy.Instance) { }

        [NonAction]
        partial void ReadyToPublishOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult ReadyToPublish(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ReadyToPublish);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ReadyToPublishOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void EditOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, nl.boxplosive.BackOffice.Mvc.Models.PublishLoyalty.PublishLoyaltyModel model);

        [NonAction]
        public override System.Web.Mvc.ActionResult Edit(nl.boxplosive.BackOffice.Mvc.Models.PublishLoyalty.PublishLoyaltyModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Edit);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            EditOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void PublishOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, nl.boxplosive.BackOffice.Mvc.Models.PublishLoyalty.PublishLoyaltyModel model);

        [NonAction]
        public override System.Web.Mvc.ActionResult Publish(nl.boxplosive.BackOffice.Mvc.Models.PublishLoyalty.PublishLoyaltyModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Publish);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            PublishOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void DownloadProductsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int selectedRuleIndex, nl.boxplosive.BackOffice.Mvc.Enums.StepType stepType, nl.boxplosive.BackOffice.Mvc.Enums.ProductsType productsType, string fileNamePrefix);

        [NonAction]
        public override System.Web.Mvc.ActionResult DownloadProducts(int selectedRuleIndex, nl.boxplosive.BackOffice.Mvc.Enums.StepType stepType, nl.boxplosive.BackOffice.Mvc.Enums.ProductsType productsType, string fileNamePrefix)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DownloadProducts);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "selectedRuleIndex", selectedRuleIndex);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "stepType", stepType);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "productsType", productsType);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "fileNamePrefix", fileNamePrefix);
            DownloadProductsOverride(callInfo, selectedRuleIndex, stepType, productsType, fileNamePrefix);
            return callInfo;
        }

        [NonAction]
        partial void GetPlaceholdersOverride(T4MVC_System_Web_Mvc_PartialViewResult callInfo, int? templateId);

        [NonAction]
        public override System.Web.Mvc.PartialViewResult GetPlaceholders(int? templateId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.GetPlaceholders);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "templateId", templateId);
            GetPlaceholdersOverride(callInfo, templateId);
            return callInfo;
        }

        [NonAction]
        partial void GetRewardPlaceholdersOverride(T4MVC_System_Web_Mvc_PartialViewResult callInfo, int? templateId, int? rewardRuleIndex);

        [NonAction]
        public override System.Web.Mvc.PartialViewResult GetRewardPlaceholders(int? templateId, int? rewardRuleIndex)
        {
            var callInfo = new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.GetRewardPlaceholders);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "templateId", templateId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "rewardRuleIndex", rewardRuleIndex);
            GetRewardPlaceholdersOverride(callInfo, templateId, rewardRuleIndex);
            return callInfo;
        }

        [NonAction]
        partial void AddProductOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string gtin);

        [NonAction]
        public override System.Web.Mvc.ActionResult AddProduct(string gtin)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddProduct);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "gtin", gtin);
            AddProductOverride(callInfo, gtin);
            return callInfo;
        }

        [NonAction]
        partial void GetProductsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string term, string parentId);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetProducts(string term, string parentId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetProducts);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "term", term);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "parentId", parentId);
            GetProductsOverride(callInfo, term, parentId);
            return callInfo;
        }

        [NonAction]
        partial void GetGroupsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string term);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetGroups(string term)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetGroups);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "term", term);
            GetGroupsOverride(callInfo, term);
            return callInfo;
        }

        [NonAction]
        partial void ValidateAndSetMultiProductsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string source);

        [NonAction]
        public override System.Web.Mvc.ActionResult ValidateAndSetMultiProducts(string source)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ValidateAndSetMultiProducts);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "source", source);
            ValidateAndSetMultiProductsOverride(callInfo, source);
            return callInfo;
        }

        [NonAction]
        partial void ConfirmProductUploadOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, string source);

        [NonAction]
        public override System.Web.Mvc.JsonResult ConfirmProductUpload(string source)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.ConfirmProductUpload);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "source", source);
            ConfirmProductUploadOverride(callInfo, source);
            return callInfo;
        }

        [NonAction]
        partial void GetDownloadProductsFileResultOverride(T4MVC_System_Web_Mvc_FileContentResult callInfo, System.Collections.Generic.IList<nl.boxplosive.BackOffice.Mvc.Models.Shared.ProductModel> products, string productSetLabel);

        [NonAction]
        public override System.Web.Mvc.FileContentResult GetDownloadProductsFileResult(System.Collections.Generic.IList<nl.boxplosive.BackOffice.Mvc.Models.Shared.ProductModel> products, string productSetLabel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_FileContentResult(Area, Name, ActionNames.GetDownloadProductsFileResult);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "products", products);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "productSetLabel", productSetLabel);
            GetDownloadProductsFileResultOverride(callInfo, products, productSetLabel);
            return callInfo;
        }

        [NonAction]
        partial void GetPromotionsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string term);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetPromotions(string term)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetPromotions);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "term", term);
            GetPromotionsOverride(callInfo, term);
            return callInfo;
        }

        [NonAction]
        partial void UploadImageOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string postedFileFieldName, string urlFieldName, string urlFieldId);

        [NonAction]
        public override System.Web.Mvc.ActionResult UploadImage(string postedFileFieldName, string urlFieldName, string urlFieldId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UploadImage);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "postedFileFieldName", postedFileFieldName);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "urlFieldName", urlFieldName);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "urlFieldId", urlFieldId);
            UploadImageOverride(callInfo, postedFileFieldName, urlFieldName, urlFieldId);
            return callInfo;
        }

        [NonAction]
        partial void UploadImageCKEditorOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, System.Web.HttpPostedFileBase upload, string ckCsrfToken);

        [NonAction]
        public override System.Web.Mvc.ActionResult UploadImageCKEditor(System.Web.HttpPostedFileBase upload, string ckCsrfToken)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UploadImageCKEditor);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "upload", upload);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "ckCsrfToken", ckCsrfToken);
            UploadImageCKEditorOverride(callInfo, upload, ckCsrfToken);
            return callInfo;
        }

        [NonAction]
        partial void SignOutUserOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, System.Web.Mvc.ActionResult actionResultOverride);

        [NonAction]
        public override System.Web.Mvc.ActionResult SignOutUser(System.Web.Mvc.ActionResult actionResultOverride)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SignOutUser);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "actionResultOverride", actionResultOverride);
            SignOutUserOverride(callInfo, actionResultOverride);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
