// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace nl.boxplosive.BackOffice.Mvc.Controllers
{
    public partial class ReclamationController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ReclamationController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected ReclamationController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DeleteMainOptionalLoyaltyCard()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteMainOptionalLoyaltyCard);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult CouponsTab()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CouponsTab);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult CouponsTabAddReservation()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CouponsTabAddReservation);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult CouponsTabClaim()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CouponsTabClaim);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult LoyaltyTab()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LoyaltyTab);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult EditCoupon()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditCoupon);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ViewResult ReturnToCurrentReclamation()
        {
            return new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.ReturnToCurrentReclamation);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ReclamationController Actions { get { return MVC.Reclamation; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Reclamation";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Reclamation";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string DeleteMainOptionalLoyaltyCard = "DeleteMainOptionalLoyaltyCard";
            public readonly string CouponsTab = "CouponsTab";
            public readonly string CouponsTabAddReservation = "CouponsTabAddReservation";
            public readonly string CouponsTabClaim = "CouponsTabClaim";
            public readonly string LoyaltyTab = "LoyaltyTab";
            public readonly string EditCoupon = "EditCoupon";
            public readonly string ReturnToCurrentReclamation = "ReturnToCurrentReclamation";
            public readonly string SignOutUser = "SignOutUser";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string DeleteMainOptionalLoyaltyCard = "DeleteMainOptionalLoyaltyCard";
            public const string CouponsTab = "CouponsTab";
            public const string CouponsTabAddReservation = "CouponsTabAddReservation";
            public const string CouponsTabClaim = "CouponsTabClaim";
            public const string LoyaltyTab = "LoyaltyTab";
            public const string EditCoupon = "EditCoupon";
            public const string ReturnToCurrentReclamation = "ReturnToCurrentReclamation";
            public const string SignOutUser = "SignOutUser";
        }


        static readonly ActionParamsClass_Index s_params_Index = new ActionParamsClass_Index();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Index IndexParams { get { return s_params_Index; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Index
        {
            public readonly string customerId = "customerId";
            public readonly string searchType = "searchType";
            public readonly string searchTerm = "searchTerm";
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_DeleteMainOptionalLoyaltyCard s_params_DeleteMainOptionalLoyaltyCard = new ActionParamsClass_DeleteMainOptionalLoyaltyCard();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DeleteMainOptionalLoyaltyCard DeleteMainOptionalLoyaltyCardParams { get { return s_params_DeleteMainOptionalLoyaltyCard; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DeleteMainOptionalLoyaltyCard
        {
            public readonly string customerId = "customerId";
            public readonly string searchType = "searchType";
            public readonly string searchTerm = "searchTerm";
        }
        static readonly ActionParamsClass_CouponsTab s_params_CouponsTab = new ActionParamsClass_CouponsTab();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_CouponsTab CouponsTabParams { get { return s_params_CouponsTab; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_CouponsTab
        {
            public readonly string model = "model";
            public readonly string id = "id";
            public readonly string page = "page";
        }
        static readonly ActionParamsClass_CouponsTabAddReservation s_params_CouponsTabAddReservation = new ActionParamsClass_CouponsTabAddReservation();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_CouponsTabAddReservation CouponsTabAddReservationParams { get { return s_params_CouponsTabAddReservation; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_CouponsTabAddReservation
        {
            public readonly string model = "model";
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_CouponsTabClaim s_params_CouponsTabClaim = new ActionParamsClass_CouponsTabClaim();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_CouponsTabClaim CouponsTabClaimParams { get { return s_params_CouponsTabClaim; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_CouponsTabClaim
        {
            public readonly string model = "model";
            public readonly string id = "id";
            public readonly string reservationId = "reservationId";
        }
        static readonly ActionParamsClass_LoyaltyTab s_params_LoyaltyTab = new ActionParamsClass_LoyaltyTab();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_LoyaltyTab LoyaltyTabParams { get { return s_params_LoyaltyTab; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_LoyaltyTab
        {
            public readonly string model = "model";
            public readonly string id = "id";
            public readonly string page = "page";
        }
        static readonly ActionParamsClass_EditCoupon s_params_EditCoupon = new ActionParamsClass_EditCoupon();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_EditCoupon EditCouponParams { get { return s_params_EditCoupon; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_EditCoupon
        {
            public readonly string reservationId = "reservationId";
            public readonly string customerId = "customerId";
            public readonly string searchType = "searchType";
            public readonly string searchTerm = "searchTerm";
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_ReturnToCurrentReclamation s_params_ReturnToCurrentReclamation = new ActionParamsClass_ReturnToCurrentReclamation();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ReturnToCurrentReclamation ReturnToCurrentReclamationParams { get { return s_params_ReturnToCurrentReclamation; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ReturnToCurrentReclamation
        {
            public readonly string customerId = "customerId";
            public readonly string searchType = "searchType";
            public readonly string searchTerm = "searchTerm";
            public readonly string selectedTab = "selectedTab";
        }
        static readonly ActionParamsClass_SignOutUser s_params_SignOutUser = new ActionParamsClass_SignOutUser();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SignOutUser SignOutUserParams { get { return s_params_SignOutUser; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SignOutUser
        {
            public readonly string actionResultOverride = "actionResultOverride";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string EditCoupon = "EditCoupon";
                public readonly string Index = "Index";
            }
            public readonly string EditCoupon = "~/Views/Reclamation/EditCoupon.cshtml";
            public readonly string Index = "~/Views/Reclamation/Index.cshtml";
            static readonly _DisplayTemplatesClass s_DisplayTemplates = new _DisplayTemplatesClass();
            public _DisplayTemplatesClass DisplayTemplates { get { return s_DisplayTemplates; } }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public partial class _DisplayTemplatesClass
            {
                static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
                public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
                public class _ViewNamesClass
                {
                    public readonly string CouponModel = "CouponModel";
                    public readonly string CouponTabModel = "CouponTabModel";
                    public readonly string LoyaltyTabModel = "LoyaltyTabModel";
                    public readonly string MutationModel = "MutationModel";
                    public readonly string PaginationModel = "PaginationModel";
                }
                public readonly string CouponModel = "~/Views/Reclamation/DisplayTemplates/CouponModel.cshtml";
                public readonly string CouponTabModel = "~/Views/Reclamation/DisplayTemplates/CouponTabModel.cshtml";
                public readonly string LoyaltyTabModel = "~/Views/Reclamation/DisplayTemplates/LoyaltyTabModel.cshtml";
                public readonly string MutationModel = "~/Views/Reclamation/DisplayTemplates/MutationModel.cshtml";
                public readonly string PaginationModel = "~/Views/Reclamation/DisplayTemplates/PaginationModel.cshtml";
            }
            static readonly _EditorTemplatesClass s_EditorTemplates = new _EditorTemplatesClass();
            public _EditorTemplatesClass EditorTemplates { get { return s_EditorTemplates; } }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public partial class _EditorTemplatesClass
            {
                static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
                public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
                public class _ViewNamesClass
                {
                }
            }
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_ReclamationController : nl.boxplosive.BackOffice.Mvc.Controllers.ReclamationController
    {
        public T4MVC_ReclamationController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int? customerId, string searchType, string searchTerm);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index(int? customerId, string searchType, string searchTerm)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "customerId", customerId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "searchType", searchType);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "searchTerm", searchTerm);
            IndexOverride(callInfo, customerId, searchType, searchTerm);
            return callInfo;
        }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, nl.boxplosive.BackOffice.Mvc.Models.Reclamation.ReclamationModel model);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index(nl.boxplosive.BackOffice.Mvc.Models.Reclamation.ReclamationModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            IndexOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void DeleteMainOptionalLoyaltyCardOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int customerId, string searchType, string searchTerm);

        [NonAction]
        public override System.Web.Mvc.ActionResult DeleteMainOptionalLoyaltyCard(int customerId, string searchType, string searchTerm)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteMainOptionalLoyaltyCard);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "customerId", customerId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "searchType", searchType);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "searchTerm", searchTerm);
            DeleteMainOptionalLoyaltyCardOverride(callInfo, customerId, searchType, searchTerm);
            return callInfo;
        }

        [NonAction]
        partial void CouponsTabOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, nl.boxplosive.BackOffice.Mvc.Models.Reclamation.CouponTabModel model, string id, int? page);

        [NonAction]
        public override System.Web.Mvc.ActionResult CouponsTab(nl.boxplosive.BackOffice.Mvc.Models.Reclamation.CouponTabModel model, string id, int? page)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CouponsTab);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "page", page);
            CouponsTabOverride(callInfo, model, id, page);
            return callInfo;
        }

        [NonAction]
        partial void CouponsTabAddReservationOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, nl.boxplosive.BackOffice.Mvc.Models.Reclamation.CouponTabModel model, string id);

        [NonAction]
        public override System.Web.Mvc.ActionResult CouponsTabAddReservation(nl.boxplosive.BackOffice.Mvc.Models.Reclamation.CouponTabModel model, string id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CouponsTabAddReservation);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            CouponsTabAddReservationOverride(callInfo, model, id);
            return callInfo;
        }

        [NonAction]
        partial void CouponsTabClaimOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, nl.boxplosive.BackOffice.Mvc.Models.Reclamation.CouponTabModel model, string id, int reservationId);

        [NonAction]
        public override System.Web.Mvc.ActionResult CouponsTabClaim(nl.boxplosive.BackOffice.Mvc.Models.Reclamation.CouponTabModel model, string id, int reservationId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CouponsTabClaim);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "reservationId", reservationId);
            CouponsTabClaimOverride(callInfo, model, id, reservationId);
            return callInfo;
        }

        [NonAction]
        partial void LoyaltyTabOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, nl.boxplosive.BackOffice.Mvc.Models.Reclamation.LoyaltyTabModel model, string id, int? page);

        [NonAction]
        public override System.Web.Mvc.ActionResult LoyaltyTab(nl.boxplosive.BackOffice.Mvc.Models.Reclamation.LoyaltyTabModel model, string id, int? page)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LoyaltyTab);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "page", page);
            LoyaltyTabOverride(callInfo, model, id, page);
            return callInfo;
        }

        [NonAction]
        partial void LoyaltyTabOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, nl.boxplosive.BackOffice.Mvc.Models.Reclamation.LoyaltyTabModel model, string id);

        [NonAction]
        public override System.Web.Mvc.ActionResult LoyaltyTab(nl.boxplosive.BackOffice.Mvc.Models.Reclamation.LoyaltyTabModel model, string id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LoyaltyTab);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            LoyaltyTabOverride(callInfo, model, id);
            return callInfo;
        }

        [NonAction]
        partial void EditCouponOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int reservationId, int customerId, nl.boxplosive.Service.ServiceModel.Customer.CustomerDetailsType searchType, string searchTerm);

        [NonAction]
        public override System.Web.Mvc.ActionResult EditCoupon(int reservationId, int customerId, nl.boxplosive.Service.ServiceModel.Customer.CustomerDetailsType searchType, string searchTerm)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditCoupon);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "reservationId", reservationId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "customerId", customerId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "searchType", searchType);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "searchTerm", searchTerm);
            EditCouponOverride(callInfo, reservationId, customerId, searchType, searchTerm);
            return callInfo;
        }

        [NonAction]
        partial void EditCouponOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, nl.boxplosive.BackOffice.Mvc.Models.Reclamation.EditCouponModel model);

        [NonAction]
        public override System.Web.Mvc.ActionResult EditCoupon(nl.boxplosive.BackOffice.Mvc.Models.Reclamation.EditCouponModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditCoupon);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            EditCouponOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void ReturnToCurrentReclamationOverride(T4MVC_System_Web_Mvc_ViewResult callInfo, int customerId, nl.boxplosive.Service.ServiceModel.Customer.CustomerDetailsType searchType, string searchTerm, string selectedTab);

        [NonAction]
        public override System.Web.Mvc.ViewResult ReturnToCurrentReclamation(int customerId, nl.boxplosive.Service.ServiceModel.Customer.CustomerDetailsType searchType, string searchTerm, string selectedTab)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.ReturnToCurrentReclamation);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "customerId", customerId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "searchType", searchType);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "searchTerm", searchTerm);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "selectedTab", selectedTab);
            ReturnToCurrentReclamationOverride(callInfo, customerId, searchType, searchTerm, selectedTab);
            return callInfo;
        }

        [NonAction]
        partial void SignOutUserOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, System.Web.Mvc.ActionResult actionResultOverride);

        [NonAction]
        public override System.Web.Mvc.ActionResult SignOutUser(System.Web.Mvc.ActionResult actionResultOverride)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SignOutUser);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "actionResultOverride", actionResultOverride);
            SignOutUserOverride(callInfo, actionResultOverride);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
