// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace T4MVC
{
    public class SharedController
    {

        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _Layout = "_Layout";
                public readonly string _Modal = "_Modal";
                public readonly string _ModalInfo = "_ModalInfo";
                public readonly string BottomBarBegin = "BottomBarBegin";
                public readonly string BottomBarEnd = "BottomBarEnd";
                public readonly string Error = "Error";
                public readonly string PlaceholderBase = "PlaceholderBase";
                public readonly string Placeholders = "Placeholders";
                public readonly string PlaceholdersReward = "PlaceholdersReward";
                public readonly string TabBarBegin = "TabBarBegin";
                public readonly string TabBarEnd = "TabBarEnd";
            }
            public readonly string _Layout = "~/Views/Shared/_Layout.cshtml";
            public readonly string _Modal = "~/Views/Shared/_Modal.cshtml";
            public readonly string _ModalInfo = "~/Views/Shared/_ModalInfo.cshtml";
            public readonly string BottomBarBegin = "~/Views/Shared/BottomBarBegin.cshtml";
            public readonly string BottomBarEnd = "~/Views/Shared/BottomBarEnd.cshtml";
            public readonly string Error = "~/Views/Shared/Error.cshtml";
            public readonly string PlaceholderBase = "~/Views/Shared/PlaceholderBase.cshtml";
            public readonly string Placeholders = "~/Views/Shared/Placeholders.cshtml";
            public readonly string PlaceholdersReward = "~/Views/Shared/PlaceholdersReward.cshtml";
            public readonly string TabBarBegin = "~/Views/Shared/TabBarBegin.cshtml";
            public readonly string TabBarEnd = "~/Views/Shared/TabBarEnd.cshtml";
            static readonly _DisplayTemplatesClass s_DisplayTemplates = new _DisplayTemplatesClass();
            public _DisplayTemplatesClass DisplayTemplates { get { return s_DisplayTemplates; } }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public partial class _DisplayTemplatesClass
            {
                static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
                public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
                public class _ViewNamesClass
                {
                    public readonly string Button = "Button";
                    public readonly string CustomBoolean = "CustomBoolean";
                    public readonly string DiscountStep = "DiscountStep";
                    public readonly string DraftableButtons = "DraftableButtons";
                    public readonly string DraftableTabs = "DraftableTabs";
                    public readonly string Enum = "Enum";
                    public readonly string Image = "Image";
                    public readonly string PaginationModel = "PaginationModel";
                    public readonly string PlaceholderImageModel = "PlaceholderImageModel";
                    public readonly string PlaceholderModel = "PlaceholderModel";
                    public readonly string PlaceholderRichTextEditorModel = "PlaceholderRichTextEditorModel";
                    public readonly string PlaceholderTextAreaModel = "PlaceholderTextAreaModel";
                    public readonly string PlaceholderTextModel = "PlaceholderTextModel";
                    public readonly string ProductsInDiscountOrRewardStep = "ProductsInDiscountOrRewardStep";
                    public readonly string RewardsStep = "RewardsStep";
                    public readonly string SavingsStep = "SavingsStep";
                    public readonly string Tab = "Tab";
                }
                public readonly string Button = "~/Views/Shared/DisplayTemplates/Button.cshtml";
                public readonly string CustomBoolean = "~/Views/Shared/DisplayTemplates/CustomBoolean.cshtml";
                public readonly string DiscountStep = "~/Views/Shared/DisplayTemplates/DiscountStep.cshtml";
                public readonly string DraftableButtons = "~/Views/Shared/DisplayTemplates/DraftableButtons.cshtml";
                public readonly string DraftableTabs = "~/Views/Shared/DisplayTemplates/DraftableTabs.cshtml";
                public readonly string Enum = "~/Views/Shared/DisplayTemplates/Enum.cshtml";
                public readonly string Image = "~/Views/Shared/DisplayTemplates/Image.cshtml";
                public readonly string PaginationModel = "~/Views/Shared/DisplayTemplates/PaginationModel.cshtml";
                public readonly string PlaceholderImageModel = "~/Views/Shared/DisplayTemplates/PlaceholderImageModel.cshtml";
                public readonly string PlaceholderModel = "~/Views/Shared/DisplayTemplates/PlaceholderModel.cshtml";
                public readonly string PlaceholderRichTextEditorModel = "~/Views/Shared/DisplayTemplates/PlaceholderRichTextEditorModel.cshtml";
                public readonly string PlaceholderTextAreaModel = "~/Views/Shared/DisplayTemplates/PlaceholderTextAreaModel.cshtml";
                public readonly string PlaceholderTextModel = "~/Views/Shared/DisplayTemplates/PlaceholderTextModel.cshtml";
                public readonly string ProductsInDiscountOrRewardStep = "~/Views/Shared/DisplayTemplates/ProductsInDiscountOrRewardStep.cshtml";
                public readonly string RewardsStep = "~/Views/Shared/DisplayTemplates/RewardsStep.cshtml";
                public readonly string SavingsStep = "~/Views/Shared/DisplayTemplates/SavingsStep.cshtml";
                public readonly string Tab = "~/Views/Shared/DisplayTemplates/Tab.cshtml";
            }
            static readonly _EditorTemplatesClass s_EditorTemplates = new _EditorTemplatesClass();
            public _EditorTemplatesClass EditorTemplates { get { return s_EditorTemplates; } }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public partial class _EditorTemplatesClass
            {
                static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
                public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
                public class _ViewNamesClass
                {
                    public readonly string CustomBoolean = "CustomBoolean";
                    public readonly string DatePicker = "DatePicker";
                    public readonly string DiscountStepModel = "DiscountStepModel";
                    public readonly string Enum = "Enum";
                    public readonly string HtmlEditor = "HtmlEditor";
                    public readonly string HttpPostedFileBase = "HttpPostedFileBase";
                    public readonly string MultiItemBrowser = "MultiItemBrowser";
                    public readonly string MultilineText = "MultilineText";
                    public readonly string NewsArticleType = "NewsArticleType";
                    public readonly string NoFormDatePicker = "NoFormDatePicker";
                    public readonly string NoFormEnum = "NoFormEnum";
                    public readonly string NoFormNumeric = "NoFormNumeric";
                    public readonly string Numeric = "Numeric";
                    public readonly string PlaceholderImageModel = "PlaceholderImageModel";
                    public readonly string PlaceholderModel = "PlaceholderModel";
                    public readonly string PlaceholderRichTextEditorModel = "PlaceholderRichTextEditorModel";
                    public readonly string PlaceholderTextAreaModel = "PlaceholderTextAreaModel";
                    public readonly string PlaceholderTextModel = "PlaceholderTextModel";
                    public readonly string ProductBrowser = "ProductBrowser";
                    public readonly string ProductsInDiscountOrRewardRule = "ProductsInDiscountOrRewardRule";
                    public readonly string PromotionStepModel = "PromotionStepModel";
                    public readonly string RepeatableTimes = "RepeatableTimes";
                    public readonly string RuleType = "RuleType";
                    public readonly string String = "String";
                    public readonly string TimePicker = "TimePicker";
                }
                public readonly string CustomBoolean = "~/Views/Shared/EditorTemplates/CustomBoolean.cshtml";
                public readonly string DatePicker = "~/Views/Shared/EditorTemplates/DatePicker.cshtml";
                public readonly string DiscountStepModel = "~/Views/Shared/EditorTemplates/DiscountStepModel.cshtml";
                public readonly string Enum = "~/Views/Shared/EditorTemplates/Enum.cshtml";
                public readonly string HtmlEditor = "~/Views/Shared/EditorTemplates/HtmlEditor.cshtml";
                public readonly string HttpPostedFileBase = "~/Views/Shared/EditorTemplates/HttpPostedFileBase.cshtml";
                public readonly string MultiItemBrowser = "~/Views/Shared/EditorTemplates/MultiItemBrowser.cshtml";
                public readonly string MultilineText = "~/Views/Shared/EditorTemplates/MultilineText.cshtml";
                public readonly string NewsArticleType = "~/Views/Shared/EditorTemplates/NewsArticleType.cshtml";
                public readonly string NoFormDatePicker = "~/Views/Shared/EditorTemplates/NoFormDatePicker.cshtml";
                public readonly string NoFormEnum = "~/Views/Shared/EditorTemplates/NoFormEnum.cshtml";
                public readonly string NoFormNumeric = "~/Views/Shared/EditorTemplates/NoFormNumeric.cshtml";
                public readonly string Numeric = "~/Views/Shared/EditorTemplates/Numeric.cshtml";
                public readonly string PlaceholderImageModel = "~/Views/Shared/EditorTemplates/PlaceholderImageModel.cshtml";
                public readonly string PlaceholderModel = "~/Views/Shared/EditorTemplates/PlaceholderModel.cshtml";
                public readonly string PlaceholderRichTextEditorModel = "~/Views/Shared/EditorTemplates/PlaceholderRichTextEditorModel.cshtml";
                public readonly string PlaceholderTextAreaModel = "~/Views/Shared/EditorTemplates/PlaceholderTextAreaModel.cshtml";
                public readonly string PlaceholderTextModel = "~/Views/Shared/EditorTemplates/PlaceholderTextModel.cshtml";
                public readonly string ProductBrowser = "~/Views/Shared/EditorTemplates/ProductBrowser.cshtml";
                public readonly string ProductsInDiscountOrRewardRule = "~/Views/Shared/EditorTemplates/ProductsInDiscountOrRewardRule.cshtml";
                public readonly string PromotionStepModel = "~/Views/Shared/EditorTemplates/PromotionStepModel.cshtml";
                public readonly string RepeatableTimes = "~/Views/Shared/EditorTemplates/RepeatableTimes.cshtml";
                public readonly string RuleType = "~/Views/Shared/EditorTemplates/RuleType.cshtml";
                public readonly string String = "~/Views/Shared/EditorTemplates/String.cshtml";
                public readonly string TimePicker = "~/Views/Shared/EditorTemplates/TimePicker.cshtml";
            }
        }
    }

}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
